import { currency } from "../domain/accounting.ts";
import { formatStatementPresetLabel, monthStartIso } from "../lib/appSupport.ts";
import { DOCUMENT_OCR_STATUS_OPTIONS } from "./documentShared.ts";
import {
  TENANT_LEDGER_ACCOUNTING_OPTIONS,
  TENANT_LEDGER_KIND_OPTIONS,
} from "./leaseShared.js";
import {
  DIALOG_CONTENT_2XL_CLASS,
  DIALOG_CONTENT_LG_CLASS,
  DIALOG_CONTENT_MD_CLASS,
  DIALOG_CONTENT_SM_CLASS,
  DIALOG_CONTENT_XL_CLASS,
} from "./workspaceUi.js";

function pickProps(source, keys) {
  return Object.fromEntries(keys.map((key) => [key, source[key]]));
}

export function buildAppDialogGroups(props) {
  const {
    activeTx,
    activeProperties,
    aiDocumentCopilotConfigured,
    aiDocumentCopilotReady,
    appSettings,
    applyAutomaticOcrToImportDraft,
    applyDocumentImportLinkSuggestion,
    assetEditorDraft,
    assetEditorOpen,
    automaticDocumentOcrAvailable,
    bankImportReviewDrafts,
    bankImportReviewOpen,
    bankImportReviewRows,
    bankImportTypeOptions,
    canCreateEditRecords,
    canDeleteRecords,
    canReconcileRecords,
    categories,
    clearLoanDraft,
    clearTenantLedgerEntryDraft,
    closeConfirmDialog,
    closeDocumentImportDialog,
    closeLeaseEditor,
    closeReleaseNotesDialog,
    confirmAndDeleteDocument,
    confirmAndDeleteLease,
    confirmAndDeleteTenantLedgerEntry,
    confirmAndDeleteUsePeriod,
    confirmDeleteTransaction,
    confirmDialog,
    currentReleaseHistory,
    dashboardQuickAddOpen,
    defaultLifeForAssetType,
    deleteAsset,
    desktopDocumentOpenApi,
    desktopUpdateState,
    displayedLeaseTenantLedgerRows,
    documentAiBusyById,
    documentImportDialogOpen,
    documentImportDraft,
    documentImportExpenseSuggestion,
    documentImportExtractedFields,
    documentImportLinkSuggestions,
    documentImportOcrBusy,
    documentImportOcrMessage,
    documentImportSuggestedTags,
    documentImportUnitOptions,
    documentImportUtilitySections,
    documentImportWorkOrderSuggestion,
    documentLinkSuggestionKindLabel,
    documentTagSuggestionSourceLabel,
    editingLoanId,
    editingTenantLedgerEntryId,
    editingUsePeriodId,
    exportTenantStatement,
    exportTenantStatementPdf,
    getTransactionReview,
    getUnitOccupancyPeriods,
    getUnitStatusForDate,
    handleClearSelectedTxnOwnerUseOverride,
    handleDeleteSelectedTxn,
    handleDuplicateSelectedTxn,
    handleEditSelectedTxn,
    handleMarkSelectedTxnTaxReviewed,
    handleToggleSelectedTxnReconciled,
    handleToggleSelectedTxnTaxChecked,
    handleUseSelectedTxnDateAsServicePeriod,
    handleVoidSelectedTxn,
    incomeCategoriesForForm,
    isTaxReviewRelevantTransaction,
    isTenantLedgerKindAllowedForTreatment,
    leaseDraft,
    leaseEditorMode,
    leasePdfInputRef,
    leaseReminderKindLabel,
    leaseReminderToneClass,
    leaseTenantLedgerHeadline,
    leaseTenantLedgerRowById,
    leaseTenantLedgerSort,
    leaseTenantLedgerSummary,
    leaseValidationDialog,
    leases,
    loanDraft,
    loanEditorOpen,
    markTransactionCapitalImprovement,
    normalizeTenantLedgerAccountingTreatment,
    onLeasePdfInputChange,
    onOpenDocumentPreview,
    onTransactionInlineAttachmentChange,
    openDocumentExternally,
    openDocumentPreview,
    openExpenseDraftFromUtilitySection,
    createExpenseTransactionsFromUtilitySections,
    openLeasePdfPicker,
    openLinkedTenantLedgerTransaction,
    openTransactionInlineAttachmentPicker,
    openAssetSourceTransaction,
    openAssetSourceWorkOrder,
    ownerContactDefaults,
    printTaxReport,
    printTenantStatement,
    properties,
    propertyDraft,
    propertyNameById,
    propertyQuickAddOpen,
    recommendedTenantLedgerAccountingTreatment,
    recommendedTenantLedgerKindForTreatment,
    releaseNotesDialog,
    releaseNotesDialogDateLabel,
    releaseNotesDialogEntry,
    releaseNotesDialogLines,
    releaseNotesDialogSummary,
    releaseNotesDialogTitle,
    releaseNotesDialogVersion,
    saveEditedAsset,
    saveImportedDocument,
    saveLease,
    saveLoan,
    saveProperty,
    saveTenantLedgerEntry,
    saveTransaction,
    saveUnitOccupancyPeriod,
    selectedDocument,
    selectedDocumentAiAnalysis,
    selectedDocumentExtractedFields,
    selectedDocumentUtilitySections,
    selectedLeaseAutomationReminders,
    selectedLeaseDocuments,
    selectedTransactionDocuments,
    selectedTxn,
    selectedTxnLinkedWorkOrder,
    selectedTxnReconcileWarning,
    selectedTxnReconcileWarningText,
    selectedTxnReviewFocusKey,
    selectedTxnToggleReconcileDisabled,
    setAssetEditorDraft,
    setAssetEditorOpen,
    setDashboardQuickAddOpen,
    setDocumentImportDialogOpen,
    setDocumentImportDraft,
    setEditingUsePeriodId,
    setForm,
    setLeaseDraft,
    setLeaseEditorMode,
    setLeaseTenantLedgerSort,
    setLoanDraft,
    setLoanEditorOpen,
    setPendingTxnAttachment,
    setPropertyDraft,
    setPropertyQuickAddOpen,
    setRentAmountTouched,
    setSelectedDocument,
    setSelectedTxn,
    setTenantLedgerDraft,
    setTenantStatementCustomEnd,
    setTenantStatementCustomStart,
    setTenantStatementPreset,
    setTxnToDelete,
    setUsePeriodDraft,
    startCreateAssetFromTransaction,
    startTenantLedgerEntryEdit,
    taxPrintDialogOpen,
    taxPrintDialogStateProps,
    taxPrintProperty,
    taxPrintScope,
    taxPrintUnitOptions,
    tenantLedgerDraft,
    tenantStatementCustomEnd,
    tenantStatementCustomStart,
    tenantStatementPreset,
    todayIso,
    transactionById,
    transactions,
    txnAttachmentInputRef,
    txnInlineAttachmentInputRef,
    txnToDelete,
    unitFilter,
    unitStatusLabel,
    units,
    usePeriodDraft,
    usePeriods,
    workOrderById,
    workOrderSuggestionConfidenceLabel,
    workOrders,
    yearFilter,
    formatPropertyLabel,
    formatUnitLabel,
    formatUsPhone,
    propertyFilter,
    form,
    createBlankForm,
    categoriesForFormType,
  } = props;

  const transactionDialogs = {
    bankImportReview: {
      ...pickProps(props, [
        "applyBankImportVendorMemoryToDraft",
        "bankImportReviewDrafts",
        "bankImportReviewRows",
        "buildBankImportReviewDraft",
        "getBankImportRowVendorMemory",
        "importReviewedBankRows",
        "setBankImportReviewOpen",
        "updateBankImportReviewDraft",
      ]),
      bankImportReviewDrafts,
      bankImportReviewRows,
      categories,
      currency,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      open: bankImportReviewOpen,
      properties: activeProperties,
      typeOptions: bankImportTypeOptions,
      units,
    },
    details: {
      canDeleteRecords,
      canReconcileRecords,
      confirmAndDeleteDocument,
      currency,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      handleClearSelectedTxnOwnerUseOverride,
      handleDeleteSelectedTxn,
      handleDuplicateSelectedTxn,
      handleEditSelectedTxn,
      handleMarkSelectedTxnTaxReviewed,
      handleMarkSelectedTxnCapitalImprovement: () => selectedTxn && markTransactionCapitalImprovement(selectedTxn.id, true),
      handleMarkSelectedTxnRepair: () => selectedTxn && markTransactionCapitalImprovement(selectedTxn.id, false),
      handleCreateAssetFromSelectedTxn: () => {
        if (!selectedTxn) return;
        const transaction = selectedTxn;
        setSelectedTxn(null);
        startCreateAssetFromTransaction(transaction);
      },
      handleToggleSelectedTxnReconciled,
      handleToggleSelectedTxnTaxChecked,
      handleUseSelectedTxnDateAsServicePeriod,
      handleVoidSelectedTxn,
      isTaxReviewRelevantTransaction,
      onTransactionInlineAttachmentChange,
      open: Boolean(selectedTxn),
      openDocumentPreview,
      openTransactionInlineAttachmentPicker,
      propertyNameById,
      selectedTransactionDocuments,
      selectedTxn,
      selectedTxnLinkedWorkOrder,
      selectedTxnReconcileWarning,
      selectedTxnReconcileWarningText,
      selectedTxnReview: getTransactionReview(selectedTxn),
      selectedTxnReviewFocusKey,
      selectedTxnToggleReconcileDisabled,
      setSelectedTxn,
      txnInlineAttachmentInputRef,
    },
    deleteTransaction: {
      confirmDeleteTransaction,
      currency,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      open: Boolean(txnToDelete),
      setTxnToDelete,
      txnToDelete,
    },
    quickAdd: {
      categories,
      categoriesForFormType,
      createBlankForm,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      form,
      incomeCategoriesForForm,
      open: dashboardQuickAddOpen,
      properties: activeProperties,
      saveTransaction,
      setDashboardQuickAddOpen,
      setForm,
      setPendingTxnAttachment,
      setRentAmountTouched,
      txnAttachmentInputRef,
      units,
    },
  };

  const documentDialogs = {
    import: {
      DOCUMENT_OCR_STATUS_OPTIONS,
      applyAutomaticOcrToImportDraft,
      applyDocumentImportLinkSuggestion,
      automaticDocumentOcrAvailable,
      closeDocumentImportDialog,
      currency,
      dialogContentXlClass: DIALOG_CONTENT_XL_CLASS,
      documentImportDialogOpen,
      documentImportDraft,
      documentImportExpenseSuggestion,
      documentImportExtractedFields,
      documentImportLinkSuggestions,
      documentImportOcrBusy,
      documentImportOcrMessage,
      documentImportSuggestedTags,
      documentImportUnitOptions,
      documentImportUtilitySections,
      documentImportWorkOrderSuggestion,
      documentLinkSuggestionKindLabel,
      documentTagSuggestionSourceLabel,
      leases,
      onOpenChange: (isOpen) => { if (!isOpen) closeDocumentImportDialog(); },
      properties: activeProperties,
      propertyNameById,
      saveImportedDocument,
      setDocumentImportDialogOpen,
      setDocumentImportDraft,
      transactions,
      workOrderSuggestionConfidenceLabel,
      workOrders,
    },
    preview: {
      aiDocumentCopilotConfigured,
      aiDocumentCopilotReady,
      automaticDocumentOcrAvailable,
      currency,
      desktopDocumentOpenApi,
      dialogContent2xlClass: DIALOG_CONTENT_2XL_CLASS,
      documentAiBusyById,
      onOpenChange: (isOpen) => { if (!isOpen) setSelectedDocument(null); },
      open: Boolean(selectedDocument),
      openDocumentExternally,
      openExpenseDraftFromUtilitySection,
      createExpenseTransactionsFromUtilitySections,
      runDocumentAiAnalysis: props.runDocumentAiAnalysis,
      selectedDocument,
      selectedDocumentAiAnalysis,
      selectedDocumentExtractedFields,
      selectedDocumentUtilitySections,
      setSelectedDocument,
    },
  };

  const leaseDialogs = {
    editor: {
      TENANT_LEDGER_ACCOUNTING_OPTIONS,
      TENANT_LEDGER_KIND_OPTIONS,
      actions: props.actions,
      appSettings,
      canCreateEditRecords,
      canDeleteRecords,
      clearTenantLedgerEntryDraft,
      closeLeaseEditor,
      confirmAndDeleteLease,
      confirmAndDeleteTenantLedgerEntry,
      confirmAndDeleteUsePeriod,
      currency,
      displayedLeaseTenantLedgerRows,
      editingTenantLedgerEntryId,
      editingUsePeriodId,
      exportTenantStatement,
      exportTenantStatementPdf,
      formatStatementPresetLabel,
      getUnitOccupancyPeriods,
      getUnitStatusForDate,
      isTenantLedgerKindAllowedForTreatment,
      leaseDraft,
      leaseEditorMode,
      leasePdfInputRef,
      leaseReminderKindLabel,
      leaseReminderToneClass,
      leaseTenantLedgerHeadline,
      leaseTenantLedgerRowById,
      leaseTenantLedgerSort,
      leaseTenantLedgerSummary,
      monthStartIso,
      normalizeTenantLedgerAccountingTreatment,
      onLeasePdfInputChange,
      openDocumentPreview: onOpenDocumentPreview || openDocumentPreview,
      openLeasePdfPicker,
      openLinkedTenantLedgerTransaction,
      printTenantStatement,
      properties,
      recommendedTenantLedgerAccountingTreatment,
      recommendedTenantLedgerKindForTreatment,
      saveLease,
      saveTenantLedgerEntry,
      saveUnitOccupancyPeriod,
      selectedLeaseAutomationReminders,
      selectedLeaseDocuments,
      setEditingUsePeriodId,
      setLeaseDraft,
      setLeaseEditorMode,
      setLeaseTenantLedgerSort,
      setTenantLedgerDraft,
      setTenantStatementCustomEnd,
      setTenantStatementCustomStart,
      setTenantStatementPreset,
      setUsePeriodDraft,
      startTenantLedgerEntryEdit,
      tenantLedgerDraft,
      tenantStatementCustomEnd,
      tenantStatementCustomStart,
      tenantStatementPreset,
      todayIso,
      transactionById,
      unitStatusLabel,
      units,
      usePeriodDraft,
    },
    validation: {
      dialogContentSmClass: DIALOG_CONTENT_SM_CLASS,
      leaseValidationDialog,
      setLeaseValidationDialog: props.setLeaseValidationDialog,
    },
  };

  const loanDialogs = {
    editor: {
      clearLoanDraft,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      editingLoanId,
      loanDraft,
      loanEditorOpen,
      properties,
      saveLoan,
      setLoanDraft,
      setLoanEditorOpen,
    },
  };

  const assetDialogs = {
    editor: {
      assetEditorDraft,
      assetEditorOpen,
      assetReviewContext: { transactions: activeTx, documents: props.documents, properties, units, leases, usePeriods, yearFilter },
      currency,
      defaultLifeForAssetType,
      deleteAsset,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      openAssetSourceTransaction,
      openAssetSourceWorkOrder,
      properties,
      saveEditedAsset,
      setAssetEditorDraft,
      setAssetEditorOpen,
      transactionById,
      units,
      workOrderById,
    },
  };

  const taxDialogs = {
    print: {
      ...taxPrintDialogStateProps,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      formatPropertyLabel,
      formatUnitLabel,
      onPrint: printTaxReport,
      open: taxPrintDialogOpen,
      properties,
      propertyFilter,
      taxPrintProperty,
      taxPrintScope,
      taxPrintUnitOptions,
      unitFilter,
      yearFilter,
    },
  };

  const releaseNotesDialogGroup = {
    current: {
      closeReleaseNotesDialog,
      currentReleaseHistory,
      desktopUpdateState,
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      releaseNotesDialog: props.releaseNotesDialog,
      releaseNotesDialogDateLabel,
      releaseNotesDialogEntry,
      releaseNotesDialogLines,
      releaseNotesDialogSummary,
      releaseNotesDialogTitle,
      releaseNotesDialogVersion,
    },
  };

  const confirmDialogGroup = {
    confirmAction: {
      closeConfirmDialog,
      confirmDialog,
      dialogContentMdClass: DIALOG_CONTENT_MD_CLASS,
    },
  };

  const propertyDialogs = {
    quickAdd: {
      dialogContentLgClass: DIALOG_CONTENT_LG_CLASS,
      formatUsPhone,
      open: propertyQuickAddOpen,
      ownerContactDefaults,
      properties,
      propertyDraft,
      saveProperty,
      setPropertyDraft,
      setPropertyQuickAddOpen,
    },
  };

  return {
    transactionDialogs,
    documentDialogs,
    leaseDialogs,
    loanDialogs,
    assetDialogs,
    taxDialogs,
    releaseNotesDialog: releaseNotesDialogGroup,
    confirmDialog: confirmDialogGroup,
    propertyDialogs,
  };
}
