import React, { Suspense, useState } from "react";
import { currency, getRentalUsePctForDate, getRentalUsePctForRange, toPctDisplay } from "./domain/accounting.ts";
import { adjustedAssetDepreciationForYear } from "./domain/assetDepreciation.ts";
import {
  buildOwnerContactDefaults,
  buildPrintableStatementHtml,
  buildStatementBranding,
  copyTextToClipboard,
  downloadTextAsFile,
  escapeHtml,
  formatStatementDateRangeLabel,
  formatStatementMonthLabel,
  formatStatementPresetLabel,
  leaseReminderKindLabel,
  leaseReminderToneClass,
  monthStartIso,
  printHtmlDocument,
  quarterStartIso,
  sanitizeFileNamePart,
} from "./lib/appSupport.ts";
import { buildOwnerMonthlyReport, buildOwnerPeriodReport, ownerMonthlyReportCsv, ownerStatementActivitySummary, ownerStatementCommunicationTxt, ownerStatementCsv, ownerStatementEmailBody, ownerStatementEmailSubject, scheduleEFriendlyCsv, statementDateRangeFromRows, summarizeOwnerMonthlyReport, tenantStatementCsv, tenantStatementSummary } from "./domain/reporting.ts";
import { documentSupportsAutomaticOcr, inferDocumentTags, normalizeDocumentOcrStatus, normalizeExtractedDocumentText, suggestDocumentType } from "./domain/documentIntelligence.ts";
import { activeProperties as getActiveProperties } from "./domain/propertyLifecycle.js";
import { isTenantLedgerKindAllowedForTreatment, normalizeTenantLedgerAccountingTreatment, recommendedTenantLedgerAccountingTreatment, recommendedTenantLedgerKindForTreatment } from "./domain/tenantLedgerPosting.ts";
import { getAssetReadiness, getAssetReviewIssues } from "./features/assets/assetReview.js";
import { useRentalStore } from "./store/useRentalStore.ts";
import { SETTINGS_SAVED_TEXT, useAppSettings } from "./store/appSettings.ts";
import { useDashboardContext } from "./store/dashboardContext.ts";
import {
  ACCESS_ROLE_LABELS,
} from "./app/accessControl.ts";
import {
  buildRentalDayAllocationWeights,
  categories,
  defaultLifeForAssetType,
  getScheduleELineIdForTransaction,
  isDeMinimisCategoryEligible,
  isTaxReviewRelevantTransaction,
} from "./app/accountingShared.js";
import { DEFAULT_DASHBOARD_YEAR } from "./app/appStorageKeys.js";
import { daysBetween, formatDaysLeft } from "./app/dateHelpers.js";
import {
  desktopDiagnosticEventClass,
  desktopDiagnosticPillClass,
  desktopUpdateBadgeClass,
  formatDesktopUpdateDate,
} from "./app/desktopUpdateShared.ts";
import {
  canAttachToTransaction,
  documentLinkSuggestionKindLabel,
  documentTagSuggestionSourceLabel,
  expenseSuggestionConfidenceLabel,
  expenseSuggestionReasonSummary,
  formatDocumentTags,
  parseDocumentTags,
  readFileAsDataUrl,
  workOrderSuggestionConfidenceLabel,
  workOrderSuggestionReasonSummary,
} from "./app/documentShared.ts";
import {
  createBlankDocumentImportDraft,
  createBlankForm,
  createBlankWorkOrderDraft,
} from "./app/draftFactories.js";
import { formatPercentInput, formatUsPhone } from "./app/formatHelpers.js";
import {
  leaseActualEndLabel,
} from "./app/leaseShared.js";
import { navItems, viewDetails } from "./app/navigationShared.js";
import {
  likelyNextViewsByView,
  prefetchDialog,
  prefetchWorkspace,
} from "./app/lazyRegistry.js";
import { AppDialogs } from "./app/AppDialogs.jsx";
import { AppWorkspaces } from "./app/AppWorkspaces.jsx";
import { AppHeaderCard } from "./app/AppHeaderCard.jsx";
import { AppSidebar } from "./app/AppSidebar.jsx";
import { useAccessSettingsController } from "./app/useAccessSettingsController.ts";
import { useAssetWorkspaceController } from "./app/useAssetWorkspaceController.js";
import { useAppDialogStateController } from "./app/useAppDialogStateController.js";
import { useAppDataSnapshot } from "./app/useAppDataSnapshot.js";
import { useAppDateScopes } from "./app/useAppDateScopes.js";
import { useAppElementRefs } from "./app/useAppElementRefs.js";
import { useAppLifecycleEffects } from "./app/useAppLifecycleEffects.ts";
import { useAppLookupMaps } from "./app/useAppLookupMaps.js";
import { useAppTransactionCollections } from "./app/useAppTransactionCollections.js";
import { useBankImportController } from "./app/useBankImportController.js";
import { useDashboardWorkspaceModel } from "./app/useDashboardWorkspaceModel.js";
import { useDashboardNavigationController } from "./app/useDashboardNavigationController.js";
import { useDashboardStatCards } from "./app/useDashboardStatCards.js";
import { useDataSafetyWorkspaceModel } from "./app/useDataSafetyWorkspaceModel.js";
import { useDataReplacementWorkflowController } from "./app/useDataReplacementWorkflowController.ts";
import { useDesktopPersistenceController } from "./app/useDesktopPersistenceController.js";
import { useRuntimePerformanceMetrics } from "./app/performanceMetrics.ts";
import { createDocumentWorkspaceController } from "./app/documentWorkspaceController.js";
import { useDocumentAttachmentWorkflow } from "./app/useDocumentAttachmentWorkflow.ts";
import { useDocumentDerivedCollections } from "./app/useDocumentDerivedCollections.ts";
import { useDesktopBridgeController } from "./app/useDesktopBridgeController.ts";
import { useDesktopRuntimeStatus } from "./app/useDesktopRuntimeStatus.ts";
import { useDocumentWorkspaceUiState } from "./app/useDocumentWorkspaceUiState.ts";
import { useDocumentReviewModel } from "./app/useDocumentReviewModel.js";
import { useLeaseTenantLedgerController } from "./app/useLeaseTenantLedgerController.js";
import { useLedgerActivityWorkspaceController } from "./app/useLedgerActivityWorkspaceController.js";
import { useLedgerTransactionActions } from "./app/useLedgerTransactionActions.js";
import { useMaintenanceWorkspaceController } from "./app/useMaintenanceWorkspaceController.js";
import { useMaintenanceReviewInbox } from "./app/useMaintenanceReviewInbox.js";
import { useLoanWorkspaceController } from "./app/useLoanWorkspaceController.js";
import { usePlanningWorkspaceAnalytics } from "./app/usePlanningWorkspaceAnalytics.js";
import { usePlanningWorkspaceActions } from "./app/usePlanningWorkspaceActions.js";
import { usePlanningWorkspaceController } from "./app/usePlanningWorkspaceController.js";
import { usePlanningWorkspaceModel } from "./app/usePlanningWorkspaceModel.js";
import { usePlanningWorkspaceNarrative } from "./app/usePlanningWorkspaceNarrative.js";
import { usePlanningReportActions } from "./app/usePlanningReportActions.js";
import { usePrimaryAction } from "./app/usePrimaryAction.js";
import { usePropertyOwnerContactController } from "./app/usePropertyOwnerContactController.js";
import { usePropertyQuickAddController } from "./app/usePropertyQuickAddController.js";
import { useRentTransactionLedgerSync } from "./app/useRentTransactionLedgerSync.js";
import { useReviewReadinessModel } from "./app/useReviewReadinessModel.js";
import { useStatementReportingController } from "./app/useStatementReportingController.js";
import { useSetupChecklistActions } from "./app/useSetupChecklistActions.js";
import { useStatementLogoController } from "./app/useStatementLogoController.js";
import { useTaxWorkspaceController } from "./app/useTaxWorkspaceController.js";
import { useTaxOverviewModel } from "./app/useTaxOverviewModel.js";
import { useTaxPacketReportingController } from "./app/useTaxPacketReportingController.js";
import { useTaxWorkspaceUiController } from "./app/useTaxWorkspaceUiController.js";
import { useTaxDerivedCalculators } from "./app/useTaxDerivedCalculators.js";
import { useTenantStatementUiState } from "./app/useTenantStatementUiState.js";
import { useTransactionEntryUiState } from "./app/useTransactionEntryUiState.js";
import { useTransactionEntryController } from "./app/useTransactionEntryController.js";
import { useTransactionFormSuggestions } from "./app/useTransactionFormSuggestions.js";
import { useTransactionWorkflowController } from "./app/useTransactionWorkflowController.js";
import { useWorkspaceFilterController } from "./app/useWorkspaceFilterController.js";
import { useWorkspacePrefetchController } from "./app/useWorkspacePrefetchController.ts";
import { useWorkOrderExpenseAction } from "./app/useWorkOrderExpenseAction.js";
import { useOcrSuggestedFieldOptions } from "./app/useOcrSuggestedFieldOptions.js";
import { useVisibleSafeSuggestionCount } from "./app/useVisibleSafeSuggestionCount.js";
import { useWorkspaceFilterOptions } from "./app/useWorkspaceFilterOptions.js";
import packageMeta from "../package.json";

const EMPTY_DOCUMENTS = [];

export default function App() {
  const { appSettings, settingsSavedVisible, setSetting: persistSetting, setDashboardCardSetting: persistDashboardCardSetting, resetToDefaults: resetStoredSettings, replaceSettings } = useAppSettings();
  const [view, setView] = useState(() => appSettings.defaultView || "dashboard");
  const runtimePerformanceMetrics = useRuntimePerformanceMetrics(view);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() => appSettings.sidebarCollapsedByDefault);
  const {
    activityFilters,
    documentFilters,
    ledgerFilters,
    activityActionFilter,
    activityCategoryFilter,
    activityEntityFilter,
    activityRoleFilter,
    activitySearch,
    documentSearch,
    documentSort,
    documentStatusFilter,
    expenseQueueShowDismissed,
    ledgerCategoryFilter,
    ledgerReconciliationFilter,
    ledgerSort,
    search,
    setDocumentSearch,
    setDocumentStatusFilter,
    setExpenseQueueShowDismissed,
    setSearch,
  } = useWorkspaceFilterController({ appSettings });

  useWorkspacePrefetchController({
    prefetchWorkspace,
    view,
    viewPrefetchMap: likelyNextViewsByView,
  });
  const { dashboardContext, yearFilter, propertyFilter, unitFilter, setYearFilter, setPropertyFilter, setUnitFilter, applyDashboardContext } = useDashboardContext({ yearFilter: DEFAULT_DASHBOARD_YEAR, propertyFilter: "all", unitFilter: "all" });

  const {
    escrowDisbursements,
    ownerStatementCustomEnd,
    ownerStatementCustomStart,
    ownerStatementNoteDraft,
    ownerStatementNoteMode,
    ownerStatementNoteTemplate,
    ownerStatementPreset,
    restoreTaxWorkspaceFromBackupData,
    setEscrowDisbursements,
    setOwnerStatementCustomEnd,
    setOwnerStatementCustomStart,
    setOwnerStatementNoteDraft,
    setOwnerStatementNoteMode,
    setTaxCarryoverByScope,
    setTaxDayOverrides,
    setTaxFiledAmountOverrides,
    setTaxPrintDialogOpen,
    setTaxPrintUnit,
    setTaxReviewCollapsed,
    taxCarryoverByScope,
    taxDayOverrides,
    taxFiledAmountOverrides,
    taxPrintDialogStateProps,
    taxPrintDialogOpen,
    taxPrintProperty,
    taxPrintScope,
    taxPrintUnit,
    taxWorkspaceUiProps,
  } = useTaxWorkspaceUiController();
  const [notice, setNotice] = useState("");
  const {
    tenantStatementCustomEnd,
    tenantStatementCustomStart,
    tenantStatementPreset,
    setTenantStatementCustomEnd,
    setTenantStatementCustomStart,
    setTenantStatementPreset,
  } = useTenantStatementUiState();
  const {
    backupImportInputRef,
    documentImportInputRef,
    leasePdfInputRef,
    statementLogoInputRef,
    txnAttachmentInputRef,
    txnInlineAttachmentInputRef,
    workOrderAttachmentInputRef,
  } = useAppElementRefs();
  const {
    editingTxnId,
    form,
    pendingDocumentExpenseSource,
    pendingTxnAttachment,
    rentAmountTouched,
    setEditingTxnId,
    setForm,
    setPendingDocumentExpenseSource,
    setPendingTxnAttachment,
    setRentAmountTouched,
  } = useTransactionEntryUiState();
  const {
    assetDraft,
    assetEditorDraft,
    assetEditorOpen,
    backupValidationBusy,
    backupValidationResult,
    closeConfirmDialog,
    confirmDialog,
    dashboardQuickAddOpen,
    openConfirmDialog,
    propertyDraft,
    propertyQuickAddOpen,
    resetPropertyDraft,
    setAssetDraft,
    setAssetEditorDraft,
    setAssetEditorOpen,
    setBackupValidationBusy,
    setBackupValidationResult,
    setDashboardQuickAddOpen,
    setPropertyDraft,
    setPropertyQuickAddOpen,
    setSettingsSectionCollapsed,
    settingsSectionCollapsed,
  } = useAppDialogStateController({ prefetchDialog });

  const {
    desktopDiagnosticsApi,
    desktopDiagnosticsBusy,
    desktopDiagnosticsReport,
    desktopDocumentAiApi,
    desktopDocumentOcrApi,
    desktopDocumentOcrState,
    desktopDocumentOpenApi,
    desktopPersistenceApi,
    desktopStatementPdfApi,
    desktopUpdaterAvailable,
    runDesktopDiagnostics,
  } = useDesktopBridgeController({ setNotice });

  const {
    documentAiBusyById,
    documentBatchOcrBusy,
    documentImportDialogOpen,
    documentImportDraft,
    documentImportOcrBusy,
    documentImportOcrMessage,
    documentImportOcrRequestIdRef,
    documentOcrBusyById,
    expenseQueueFocusDocumentId,
    selectedDocument,
    selectedWorkOrderAttachmentId,
    setDocumentAiBusyById,
    setDocumentBatchOcrBusy,
    setDocumentImportDialogOpen,
    setDocumentImportDraft,
    setDocumentImportOcrBusy,
    setDocumentImportOcrMessage,
    setDocumentOcrBusyById,
    setExpenseQueueFocusDocumentId,
    setSelectedDocument,
    setSelectedWorkOrderAttachmentId,
  } = useDocumentWorkspaceUiState();

  const accessRole = appSettings.accessRole || "admin";
  const accessRoleLabel = ACCESS_ROLE_LABELS[accessRole] || "Admin";
  const { transactions, assets, documents, leases, tenantLedgerEntries, vendors, workOrders, loans, loanPayments, usePeriods, recurringTemplates, recurringDrafts, properties, units, activityLog, actions } = useRentalStore({ actorName: appSettings.operatorName, actorRole: accessRoleLabel });
  const activeProperties = getActiveProperties(properties);
  const {
    addPlanningActionFromCapitalTarget,
    addPlanningActionItem,
    clearPlanningScenarioSelection,
    clonePlanningScenario,
    deletePlanningActionItem,
    deletePlanningManualProject,
    deletePlanningScenario,
    deletePlanningScenarioEvent,
    draftPlanningManualProjectFromTarget,
    editPlanningManualProject,
    editPlanningScenarioEvent,
    getPlanningRentStrategy,
    getPlanningTurnoverInput,
    getPlanningUnitOverride,
    loadPlanningScenario,
    planningActionItems,
    planningActiveScenario,
    planningActiveScenarioId,
    planningAssumptions,
    planningBaselineScenario,
    planningBaselineScenarioId,
    planningDebtPayoffPlan,
    planningEventDraft,
    planningEventPropertyId,
    planningEventUnitOptions,
    planningExitPlan,
    planningForecastOptions,
    planningGoals,
    planningManualProjects,
    planningProjectDraft,
    planningProjectLinkedAssetOptions,
    planningProjectPropertyId,
    planningProjectUnitOptions,
    planningRentStrategies,
    planningSavedScenarios,
    planningScenarioEvents,
    planningScenarioNameDraft,
    planningScenarioNotesDraft,
    planningScenarioOverrides,
    planningSubtab,
    planningTriggers,
    planningTurnoverInputs,
    resetPlanningEventDraft,
    resetPlanningProjectDraft,
    resetPlanningWorkspace,
    restorePlanningWorkspaceFromBackupData,
    savePlanningManualProject,
    savePlanningManualProjectFromTarget,
    savePlanningScenarioAsNew,
    savePlanningScenarioBranch,
    savePlanningScenarioEvent,
    setPlanningAssumptions,
    setPlanningBaselineScenarioId,
    setPlanningDebtPayoffPlan,
    setPlanningEventDraft,
    setPlanningExitPlan,
    setPlanningForecastOptions,
    setPlanningGoals,
    setPlanningProjectDraft,
    setPlanningRentStrategy,
    setPlanningScenarioEvents,
    setPlanningScenarioNameDraft,
    setPlanningScenarioNotesDraft,
    setPlanningSubtab,
    setPlanningTriggers,
    setPlanningTurnoverInput,
    setPlanningUnitOverride,
    updatePlanningActionItem,
    updatePlanningScenario,
  } = usePlanningWorkspaceController({
    assets,
    openConfirmDialog,
    properties,
    propertyFilter,
    setNotice,
    setPropertyFilter,
    setUnitFilter,
    setView,
    units,
  });

  const currentView = viewDetails[view] || viewDetails.dashboard;
  const {
    activeAccessRoleOption,
    addAuditEntry,
    aiDocumentCopilotConfigured,
    aiDocumentCopilotReady,
    canCreateEditRecords,
    canDeleteRecords,
    canManageAccessProfile,
    canManageDataAdmin,
    canReconcileRecords,
    canReviewDocuments,
    requirePermission,
    resetToDefaults,
    restoreLocalAdminAccess,
    roleAccessSummary,
    setSetting,
    toggleDashboardCardSetting,
  } = useAccessSettingsController({
    accessRole,
    accessRoleLabel,
    actions,
    appSettings,
    desktopDocumentAiApi,
    persistDashboardCardSetting,
    persistSetting,
    resetStoredSettings,
    setNotice,
  });
  const {
    propertyOwnerDrafts,
    savePropertyOwnerContact,
    setPropertyOwnerDrafts,
  } = usePropertyOwnerContactController({
    actions,
    properties,
    requirePermission,
    setNotice,
  });
  const { currentAppDataSnapshot, hasAnyData } = useAppDataSnapshot({
    assets,
    documents,
    leases,
    loanPayments,
    loans,
    properties,
    recurringDrafts,
    recurringTemplates,
    tenantLedgerEntries,
    transactions,
    units,
    usePeriods,
    vendors,
    workOrders,
  });
  const {
    applyLeaseAutomation,
    autoBackupStatusLabel,
    checkForDesktopUpdates,
    closeReleaseNotesDialog,
    createAutoBackupNow,
    currentAppVersion,
    currentReleaseHistory,
    currentReleaseNotesEntry,
    desktopUpdateBusy,
    desktopUpdateCanRestart,
    desktopUpdateCheckedAtLabel,
    desktopUpdateMessage,
    desktopUpdateProgress,
    desktopUpdateReleaseDateLabel,
    desktopUpdateState,
    desktopUpdateStatusKey,
    desktopUpdateStatusLabel,
    effectiveUpdateReleaseNotes,
    exportDataBackup,
    exportLatestAutoBackup,
    installDesktopUpdateNow,
    isDataHydrated,
    leaseAutomationDefaults,
    leaseAutomationLastRunAt,
    leaseAutomationLastRunLabel,
    leaseAutomationReminders,
    openCurrentReleaseNotesDialog,
    openDesktopDataFolder,
    openUpdateReleaseNotesDialog,
    persistenceHealth,
    persistenceLastError,
    performanceMetrics,
    reloadDesktopPersistenceData,
    releaseNotesDialog,
    restorePointBusy,
    releaseNotesDialogDateLabel,
    releaseNotesDialogEntry,
    releaseNotesDialogLines,
    releaseNotesDialogSummary,
    releaseNotesDialogTitle,
    releaseNotesDialogVersion,
    runLeaseAutomationNow,
    updateReleaseNotesEntry,
    updateTargetVersion,
  } = useDesktopPersistenceController({
    activityLog,
    addAuditEntry,
    actions,
    appSettings,
    assets,
    bundledAppVersion: String(packageMeta.version || ""),
    desktopUpdaterAvailable,
    documents,
    formatDesktopUpdateDate,
    hasAnyData,
    leases,
    loanPayments,
    loans,
    openConfirmDialog,
    planningActionItems,
    planningActiveScenarioId,
    planningAssumptions,
    planningBaselineScenarioId,
    planningDebtPayoffPlan,
    planningEventDraft,
    planningExitPlan,
    planningForecastOptions,
    planningGoals,
    planningManualProjects,
    planningProjectDraft,
    planningRentStrategies,
    planningSavedScenarios,
    planningScenarioEvents,
    planningScenarioOverrides,
    planningTriggers,
    planningTurnoverInputs,
    properties,
    recurringDrafts,
    recurringTemplates,
    replaceSettings,
    requirePermission,
    restorePlanningWorkspaceFromBackupData,
    restoreTaxWorkspaceFromBackupData,
    setNotice,
    escrowDisbursements,
    taxCarryoverByScope,
    taxDayOverrides,
    taxFiledAmountOverrides,
    tenantLedgerEntries,
    transactions,
    units,
    usePeriods,
    vendors,
    workOrders,
  });
  const {
    currentDataStatus,
    demoLoadWarning,
    realDataChecklist,
  } = useDataSafetyWorkspaceModel({
    state: currentAppDataSnapshot,
    persistenceHealth,
    backupValidationResult,
  });
  const {
    automaticDocumentOcrAvailable,
    desktopDiagnosticsCheckedAtLabel,
    desktopDiagnosticsRecentEvents,
  } = useDesktopRuntimeStatus({
    desktopDiagnosticsReport,
    desktopDocumentOcrApi,
    desktopDocumentOcrState,
    formatDesktopUpdateDate,
  });
  const { getSuggestedFieldOptions } = useOcrSuggestedFieldOptions({ pendingDocumentExpenseSource });
  const { recurringThroughDate, todayIso } = useAppDateScopes({ yearFilter });

  const { activeTx, transactionVendorMemories } = useAppTransactionCollections({ transactions });

  const {
    activityActionOptions,
    activityCategoryOptions,
    activityEntityOptions,
    activityRoleOptions,
    filteredActivityLog,
    filteredTransactions,
    getTransactionReview,
    ledgerCategories,
    ledgerTransactions,
    transactionReviewById,
    transactionReviewInbox,
  } = useLedgerActivityWorkspaceController({
    activityActionFilter,
    activityCategoryFilter,
    activityEntityFilter,
    activityLog,
    activityRoleFilter,
    activitySearch,
    activeTx,
    assets,
    documents,
    isTaxReviewRelevantTransaction,
    ledgerCategoryFilter,
    ledgerReconciliationFilter,
    ledgerSort,
    propertyFilter,
    search,
    unitFilter,
    yearFilter,
  });
  const {
    dashboardAsOfDate,
    dashboardLeases,
    dashboardScopedLeases,
    dashboardScopedTransactions,
    dashboardPropertySnapshot,
    dashboardPropertySnapshotSummary,
    dashboardRentTransactions,
    dashboardTransactions,
    getUnitOccupancyPeriods,
    getUnitStatusForDate,
    isHistoricalDashboard,
    leaseCoverageByProperty,
    unitStatusLabel,
  } = useDashboardWorkspaceModel({
    activeTx,
    leases,
    properties,
    propertyFilter,
    todayIso,
    unitFilter,
    units,
    usePeriods,
    yearFilter,
  });

  const {
    formatPropertyLabel,
    formatUnitLabel,
    propertyNameById,
    unitFilterOptions,
  } = useWorkspaceFilterOptions({
    properties,
    propertyFilter,
    units,
  });
  const {
    assetById,
    leaseById,
    loanById,
    transactionById,
    vendorById,
    workOrderById,
  } = useAppLookupMaps({
    assets,
    leases,
    loans,
    transactions,
    vendors,
    workOrders,
  });
  const {
    WORK_ORDER_PRIORITY_OPTIONS,
    confirmAndDeleteVendor,
    createWorkOrder,
    editingVendorId,
    hiddenMaintenanceVendorCount,
    maintenanceRollup,
    maintenanceStatusFilter,
    maintenanceStatusSummary,
    maintenanceTotalCost,
    maintenanceVendors,
    maintenanceVisibleWorkOrders,
    pendingDocumentWorkOrderSource,
    resetMaintenanceWorkspaceState,
    resetVendorEditor,
    saveVendor,
    setMaintenanceStatusFilter,
    setPendingDocumentWorkOrderSource,
    setVendorDraft,
    setWorkOrderDraft,
    startEditingVendor,
    vendorDraft,
    workOrderDraft,
    workOrderUnitOptions,
  } = useMaintenanceWorkspaceController({
    actions,
    leases,
    properties,
    propertyFilter,
    requirePermission,
    setDocumentStatusFilter,
    setExpenseQueueShowDismissed,
    setNotice,
    todayIso,
    transactions,
    unitFilter,
    units,
    vendors,
    workOrders,
    openConfirmDialog,
    formatUsPhone,
  });
  const {
    bankImportDefaults,
    bankImportFileName,
    bankImportImportedCount,
    bankImportInputRef,
    bankImportMatchCount,
    bankImportMatchRule,
    bankImportMatchRuleOptions,
    bankImportMatches,
    bankImportReviewDrafts,
    bankImportReviewOpen,
    bankImportReviewRows,
    bankImportRows,
    bankImportSkippedRows,
    bankImportTypeOptions,
    bankImportUnitOptions,
    bankImportUnmatchedRows,
    applyBankImportVendorMemoryToDraft,
    applyBankImportMatches,
    buildBankImportReviewDraft,
    clearBankImportPreview,
    getBankImportRowVendorMemory,
    importReviewedBankRows,
    onBankImportInputChange,
    onBankImportMatchRuleChange,
    openBankImportPicker,
    openBankImportReview,
    setBankImportDefaults,
    setBankImportReviewOpen,
    updateBankImportReviewDraft,
  } = useBankImportController({
    actions,
    activeTx,
    addAuditEntry,
    categories,
    isTaxReviewRelevantTransaction,
    properties,
    propertyFilter,
    requirePermission,
    setNotice,
    setView,
    transactionById,
    transactions,
    units,
  });
  const {
    expectedRecurringTransactions,
    markTransactionsTaxReviewed,
    markTransactionSupportUnavailable,
    postDueRecurringTransactions,
    reconcileTransactions,
    useTransactionDatesAsServicePeriods,
  } = useLedgerTransactionActions({
    actions,
    activeTx,
    propertyFilter,
    recurringTemplates,
    recurringThroughDate,
    requirePermission,
    setNotice,
    transactionById,
    unitFilter,
    yearFilter,
  });
  const maintenanceReviewInbox = useMaintenanceReviewInbox({
    assets,
    documents,
    maintenanceVisibleWorkOrders,
    todayIso,
    transactions,
    vendors,
  });
  const {
    effectiveLoanPaymentDeductibleInterest,
    effectiveLoanPaymentRentalUsePct,
    effectiveTransactionDeductibleAmount,
    observedLoanDefaultsById,
  } = useTaxDerivedCalculators({
    leases,
    loanById,
    loanPayments,
    loans,
    units,
    usePeriods,
  });
  useRentTransactionLedgerSync({
    actions,
    isDataHydrated,
    leases,
    tenantLedgerEntries,
    transactions,
  });

  const {
    documentImportUnitOptions,
    filteredDocuments,
    leaseDocCountById,
    scopedLeaseAutomationReminders,
  } = useDocumentDerivedCollections({
    documentImportDraft,
    documents,
    leaseAutomationReminders,
    propertyFilter,
    unitFilter,
    units,
  });

  const {
    clearTenantLedgerEntryDraft,
    closeLeaseEditor,
    confirmAndDeleteLease,
    confirmAndDeleteTenantLedgerEntry,
    confirmAndDeleteUsePeriod,
    displayedLeaseTenantLedgerRows,
    editingTenantLedgerEntryId,
    editingUsePeriodId,
    leaseDraft,
    leaseEditorMode,
    leaseTenantLedgerHeadline,
    leaseTenantLedgerRowById,
    leaseTenantLedgerSort,
    leaseTenantLedgerSummary,
    leaseValidationDialog,
    openLease,
    openLeaseForUnit,
    onLeasePdfInputChange,
    openNewLeaseForUnit,
    openLinkedTenantLedgerTransaction,
    openOccupancyEditor,
    openLeasePdfPicker,
    saveLease,
    saveTenantLedgerEntry,
    saveUnitOccupancyPeriod,
    selectedLeaseAutomationReminders,
    selectedLeaseDocuments,
    setEditingUsePeriodId,
    setLeaseDraft,
    setLeaseEditorMode,
    setLeaseTenantLedgerSort,
    setLeaseValidationDialog,
    setTenantLedgerDraft,
    setUsePeriodDraft,
    startTenantLedgerEntryEdit,
    tenantLedgerDraft,
    usePeriodDraft,
  } = useLeaseTenantLedgerController({
    actions,
    appSettings,
    confirmDestructiveActions: appSettings.confirmDestructiveActions,
    currency,
    documents,
    inferDocumentTags,
    leaseAutomationReminders,
    leasePdfInputRef,
    openConfirmDialog,
    openTransaction: (...args) => openTransaction(...args),
    prefetchDialog,
    readFileAsDataUrl,
    requirePermission,
    setNotice,
    tenantLedgerEntries,
    todayIso,
    transactionById,
    leases,
    usePeriods,
  });
  const {
    navigateWithDashboardContext,
    openLeaseDetail,
    openPlanningWorkspace,
    openPropertyFromSnapshot,
    seeAllLeases,
    seeAllNeedsReview,
    seeAllProperties,
    seeAllTransactions,
  } = useDashboardNavigationController({
    applyDashboardContext,
    dashboardContext,
    openLease,
    setPlanningSubtab,
    setView,
  });

  const {
    buildDocumentAiContext,
    describeDocumentOwnership,
    dismissedExpenseReviewCount,
    dismissedWorkOrderReviewCount,
    documentExpenseReviewRecordById,
    documentExpenseReviewRecords,
    documentImportExpenseSuggestion,
    documentImportExtractedFields,
    documentImportLinkSuggestions,
    documentImportSuggestedTags,
    documentImportUtilitySections,
    documentImportWorkOrderSuggestion,
    documentWorkOrderReviewRecordById,
    documentWorkOrderReviewRecords,
    focusedExpenseQueueDocumentId,
    getDocumentExpenseSuggestion,
    getDocumentExtractedFields,
    getDocumentImportLinkSuggestions,
    getDocumentImportSuggestedTags,
    getDocumentLinkSuggestions,
    getDocumentLinkedWorkOrder,
    getDocumentSuggestedTags,
    getDocumentUtilitySections,
    getDocumentWorkOrderSuggestion,
    getNextExpenseQueueRecord,
    getNextWorkOrderQueueRecord,
    pendingExpenseReviewCount,
    pendingHighConfidenceExpenseReviewCount,
    pendingHighConfidenceWorkOrderReviewCount,
    pendingWorkOrderReviewCount,
    selectedDocumentAiAnalysis,
    selectedDocumentExtractedFields,
    selectedDocumentUtilitySections,
    selectExpenseQueueFilter,
    selectWorkOrderQueueFilter,
    visibleAutomaticOcrDocuments,
    visibleDocuments,
    visibleDocumentsMissingIndex,
    visibleExpenseReviewRecords,
    visibleWorkOrderReviewRecords,
    workOrderDocumentCountById,
  } = useDocumentReviewModel({
    isActive: view === "documents" || view === "review",
    isDocumentImportOpen: documentImportDialogOpen,
    documentImportDraft,
    documentSearch,
    documentSort,
    documentStatusFilter,
    documents,
    expenseQueueFocusDocumentId,
    expenseQueueShowDismissed,
    filteredDocuments,
    leaseById,
    leases,
    propertyNameById,
    properties,
    selectedDocument,
    setDocumentStatusFilter,
    setExpenseQueueShowDismissed,
    transactionById,
    transactions,
    units,
    vendorById,
    vendors,
    workOrderById,
    workOrders,
  });

  useAppLifecycleEffects({
    actions,
    appSettings,
    applyLeaseAutomation,
    isDataHydrated,
    leaseAutomationDefaults,
    leases,
    notice,
    propertyFilter,
    recurringThroughDate,
    setNotice,
    setPendingDocumentExpenseSource,
    setPendingDocumentWorkOrderSource,
    setUnitFilter,
    tenantLedgerEntries,
    todayIso,
    units,
    view,
  });

  const {
    categoriesForFormType,
    incomeCategoriesForForm,
  } = useTransactionFormSuggestions({
    categories,
    form,
    leases,
    properties,
    rentAmountTouched,
    setForm,
    setRentAmountTouched,
    units,
  });

  const {
    attachDocumentToTransaction,
    onWorkOrderAttachmentInputChange,
    openWorkOrderAttachmentPicker,
    openWorkOrderDocuments,
  } = useDocumentAttachmentWorkflow({
    actions,
    canAttachToTransaction,
    inferDocumentTags,
    readFileAsDataUrl,
    selectedWorkOrderAttachmentId,
    setDocumentSearch,
    setDocumentStatusFilter,
    setNotice,
    setPropertyFilter,
    setSelectedWorkOrderAttachmentId,
    setUnitFilter,
    setView,
    vendorById,
    workOrderAttachmentInputRef,
    workOrderById,
  });

  const {
    confirmDeleteTransaction,
    editReturnView,
    handleClearSelectedTxnOwnerUseOverride,
    handleDeleteSelectedTxn,
    handleDuplicateSelectedTxn,
    handleEditSelectedTxn,
    handleMarkSelectedTxnTaxReviewed,
    handleToggleSelectedTxnReconciled,
    handleToggleSelectedTxnTaxChecked,
    handleUseSelectedTxnDateAsServicePeriod,
    handleVoidSelectedTxn,
    onTransactionInlineAttachmentChange,
    openTransaction,
    openTransactionInlineAttachmentPicker,
    selectedTransactionDocuments,
    selectedTxn,
    selectedTxnReviewFocusKey,
    selectedTxnLinkedWorkOrder,
    selectedTxnReconcileWarning,
    selectedTxnReconcileWarningText,
    selectedTxnToggleReconcileDisabled,
    setEditReturnView,
    setSelectedTxn,
    setTxnToDelete,
    startEdit,
    txnToDelete,
  } = useTransactionWorkflowController({
    actions,
    addAuditEntry,
    attachDocumentToTransaction,
    createBlankForm,
    currency,
    documents,
    formatPercentInput,
    prefetchDialog,
    readOnlyView: view,
    requirePermission,
    selectedTxnSourceView: view,
    setEditingTxnId,
    setForm,
    setNotice,
    setPendingDocumentExpenseSource,
    setPendingTxnAttachment,
    setSearch,
    setView,
    setRentAmountTouched,
    startView: view,
    transactionById,
    txnAttachmentInputRef,
    txnInlineAttachmentInputRef,
    workOrders,
  });
  const createWorkOrderExpense = useWorkOrderExpenseAction({
    actions,
    openTransaction,
    setNotice,
    todayIso,
    transactionById,
    vendorById,
  });

  const deMinimisThreshold = appSettings.deMinimisHasAFS ? 5000 : 2500;
  const {
    autoOwnerUsePct,
    applyVendorMemoryToForm,
    clearTransactionForm,
    deMinimisPreview,
    mileagePreview,
    onTransactionAttachmentInputChange,
    openDashboardQuickAdd,
    openDashboardQuickAddForScope,
    openTransactionAttachmentPicker,
    preview,
    saveTransaction,
    showDeMinimisControls,
    vendorMemorySuggestion,
  } = useTransactionEntryController({
    actions,
    appSettings,
    attachDocumentToTransaction,
    canAttachToTransaction,
    categories,
    createBlankForm,
    currency,
    deMinimisThreshold,
    documents,
    editReturnView,
    editingTxnId,
    form,
    getRentalUsePctForDate,
    getRentalUsePctForRange,
    isDeMinimisCategoryEligible,
    isTaxReviewRelevantTransaction,
    leases,
    pendingDocumentExpenseSource,
    pendingTxnAttachment,
    prefetchDialog,
    properties,
    recurringThroughDate,
    requirePermission,
    setDashboardQuickAddOpen,
    setDocumentStatusFilter,
    setEditingTxnId,
    setExpenseQueueFocusDocumentId,
    setExpenseQueueShowDismissed,
    setForm,
    setNotice,
    setPendingDocumentExpenseSource,
    setPendingTxnAttachment,
    setPropertyQuickAddOpen,
    setRentAmountTouched,
    setEditReturnView,
    setView,
    transactionVendorMemories,
    txnAttachmentInputRef,
    units,
    usePeriods,
  });

  const {
    annualLoanSummary,
    dashboardFiltersSummary,
    dashboardOpenReviewItems,
    deductibleExpensesTrend,
    flags,
    grossRentTrend,
    metrics,
    propertyFilterLabel,
    scheduleEBreakdown,
    taxReviewCpaNotes,
    taxReviewOpenCount,
    taxReviewSections,
    unitFilterLabel,
    yearScopedLoanPayments,
    yearScopedTransactions,
    copyTaxReviewNotes,
  } = useTaxOverviewModel({
    activeTx,
    adjustedAssetDepreciationForYear,
    appSettings,
    assets,
    currency,
    deMinimisThreshold,
    effectiveLoanPaymentDeductibleInterest,
    effectiveTransactionDeductibleAmount,
    getScheduleELineIdForTransaction,
    isTaxActive: view === "tax",
    leases,
    loanPayments,
    loans,
    propertyFilter,
    propertyNameById,
    setNotice,
    setTaxReviewCollapsed,
    todayIso,
    unitFilter,
    units,
    usePeriods,
    yearFilter,
  });

  const ownerContactDefaults = buildOwnerContactDefaults(appSettings);

  const { onStatementLogoInputChange } = useStatementLogoController({ setNotice, setSetting });

  const {
    loadDemoData,
    onBackupImportInputChange,
    openBackupImportPicker,
    validateLatestBackup,
  } = useDataReplacementWorkflowController({
    actions,
    appSettings,
    autoBackupStatusLabel,
    backupImportInputRef,
    bankImportInputRef,
    clearBankImportPreview,
    closeLeaseEditor,
    currentDataStatus,
    demoLoadWarning,
    formatDesktopUpdateDate,
    hasAnyData,
    openConfirmDialog,
    replaceSettings,
    requirePermission,
    resetMaintenanceWorkspaceState,
    restorePlanningWorkspaceFromBackupData,
    restoreTaxWorkspaceFromBackupData,
    setBackupValidationBusy,
    setBackupValidationResult,
    setDashboardQuickAddOpen,
    setDocumentSearch,
    setDocumentStatusFilter,
    setEditingTxnId,
    setExpenseQueueShowDismissed,
    setForm,
    setNotice,
    setPendingTxnAttachment,
    setPropertyFilter,
    setPropertyQuickAddOpen,
    setSelectedDocument,
    setSelectedTxn,
    setUnitFilter,
    setView,
    txnAttachmentInputRef,
    txnInlineAttachmentInputRef,
  });
  const {
    setSetupChecklistOverride,
    toggleSetupChecklistShowFull,
  } = useSetupChecklistActions({ appSettings, setSetting });

  const {
    applyPlanningPreset,
    planningAssumptionAuditRows,
    planningCapitalMonthlyTarget,
    planningCapitalRunway,
    planningCapitalTargetSections,
    planningCapitalTargetsMerged,
    planningCapitalTimeline,
    planningDataConfidence,
    planningDebtPayoff,
    planningDecisionComparison,
    planningExcludedBuildingAssetCount,
    planningExitAnalysis,
    planningFinancingComparison,
    planningForecastOptionInputs,
    planningGoalStatus,
    planningHealthSummary,
    planningHorizonDisplayMetrics,
    planningHorizonMonths,
    planningHorizonShortLabel,
    planningMilestones,
    planningMustFundWarnings,
    planningNearTermCapitalCost,
    planningNearTermCapitalTargets,
    planningNearTermReserveTarget,
    planningNextCapitalTarget,
    planningProjection,
    planningPropertySnapshots,
    planningRecommendations,
    planningRecommendedMoves,
    planningRentStrategy,
    planningReserveGap,
    planningReserveSummary,
    planningRows,
    planningScenarioEventInputs,
    planningScenarioIsDirty,
    planningScenarioOverrideInputs,
    planningScopeLabel,
    planningScopeUnits,
    planningSummary,
    planningTaxProjection,
    planningTriggerAlerts,
    planningTurnoverPlanner,
    planningUnitEconomicsRows,
    planningUnitFilterIgnored,
    planningUpcomingChanges,
  } = usePlanningWorkspaceModel({
    activeTx,
    assets,
    formatPropertyLabel,
    leases,
    loans,
    planningActiveScenario,
    planningAssumptions,
    planningBaselineScenario,
    planningDebtPayoffPlan,
    planningExitPlan,
    planningForecastOptions,
    planningGoals,
    planningManualProjects,
    planningRentStrategies,
    planningScenarioEvents,
    planningScenarioNameDraft,
    planningScenarioNotesDraft,
    planningScenarioOverrides,
    planningTriggers,
    planningTurnoverInputs,
    properties,
    propertyFilter,
    setPlanningAssumptions,
    todayIso,
    unitFilter,
    units,
    usePeriods,
  });
  const {
    applyPlanningRecommendedMove,
    applyPlanningScenarioTemplate,
    openPlanningReviewInboxItem,
  } = usePlanningWorkspaceActions({
    currency,
    draftPlanningManualProjectFromTarget,
    getPlanningTurnoverInput,
    planningAssumptions,
    planningCapitalMonthlyTarget,
    planningDecisionComparison,
    planningMilestones,
    planningNextCapitalTarget,
    planningRecommendedMoves,
    planningRentStrategy,
    planningTurnoverPlanner,
    planningUnitEconomicsRows,
    properties,
    propertyFilter,
    resetPlanningEventDraft,
    savePlanningManualProjectFromTarget,
    setNotice,
    setPlanningAssumptions,
    setPlanningEventDraft,
    setPlanningScenarioEvents,
    setPlanningSubtab,
    todayIso,
  });
  const {
    planningCapitalChartData,
    planningDecisionDashboard,
    planningOutcomeHighlights,
    planningScenarioChartData,
    planningScenarioComparisons,
    planningScenarioComparisonsExtended,
    planningScenarioDiffRows,
    planningScenarioRange,
    planningScenarioTimelineRows,
    planningScenarioTimelineVisual,
    planningSensitivityRows,
  } = usePlanningWorkspaceAnalytics({
    activeTx,
    currency,
    formatPropertyLabel,
    isPlanningActive: view === "planning",
    leases,
    loans,
    planningActiveScenario,
    planningAssumptions,
    planningBaselineScenario,
    planningCapitalTargetsMerged,
    planningCapitalTimeline,
    planningDataConfidence,
    planningDebtPayoffPlan,
    planningForecastOptionInputs,
    planningForecastOptions,
    planningGoals,
    planningHealthSummary,
    planningHorizonMonths,
    planningMilestones,
    planningProjection,
    planningRecommendedMoves,
    planningRentStrategies,
    planningRows,
    planningScenarioEvents,
    planningScenarioNotesDraft,
    planningScenarioOverrides,
    planningScopeLabel,
    planningSummary,
    planningTurnoverInputs,
    properties,
    propertyFilter,
    todayIso,
    units,
    usePeriods,
  });
  const {
    dashboardPlanningWatch,
    planningMemoHtml,
    planningMemoText,
    planningOpenActionItems,
    planningOverviewJumpCards,
    planningReviewInbox,
    planningSubtabGuide,
  } = usePlanningWorkspaceNarrative({
    appSettings,
    currency,
    formatPropertyLabel,
    isPlanningActive: view === "planning",
    isHistoricalDashboard,
    planningActionItems,
    planningActiveScenario,
    planningAssumptions,
    planningAssumptionAuditRows,
    planningBaselineScenario,
    planningCapitalMonthlyTarget,
    planningCapitalTargetsMerged,
    planningDataConfidence,
    planningDecisionDashboard,
    planningExitPlan,
    planningGoalStatus,
    planningGoals,
    planningHealthSummary,
    planningHorizonDisplayMetrics,
    planningHorizonMonths,
    planningHorizonShortLabel,
    planningManualProjects,
    planningMilestones,
    planningNextCapitalTarget,
    planningRecommendedMoves,
    planningRecommendations,
    planningReserveGap,
    planningRentStrategyPricedUnitCount: planningRentStrategy.summary.pricedUnitCount,
    planningRows,
    planningScenarioComparisonsExtended,
    planningScenarioDiffRows,
    planningScenarioEvents,
    planningScenarioIsDirty,
    planningScenarioNotesDraft,
    planningScenarioOverrides,
    planningScopeLabel,
    planningSubtab,
    planningSummary,
    planningTriggerAlerts,
    planningTriggers,
    planningForecastOptions,
    todayIso,
  });
  const {
    copyPlanningMemo,
    exportPlanningMemoPdf,
    exportPlanningMemoText,
    exportPlanningReport,
    printPlanningMemo,
  } = usePlanningReportActions({
    addAuditEntry,
    copyTextToClipboard,
    desktopStatementPdfApi,
    downloadTextAsFile,
    planningAssumptions,
    planningMemoHtml,
    planningMemoText,
    planningReserveSummary,
    planningRows,
    planningScopeLabel,
    planningSummary,
    printHtmlDocument,
    propertyFilter,
    sanitizeFileNamePart,
    setNotice,
    yearFilter,
  });
  const {
    carryoverInputValue,
    carryoverScope,
    clearTaxFiledAmountOverride,
    clearEscrowDisbursementDraft,
    confirmResetTaxDayOverride,
    createEscrowTransaction,
    dashboardUnitAllocationWeight,
    defaultEscrowLoanOptions,
    deleteEscrowDisbursement,
    editingEscrowDisbursementId,
    escrowDisbursementDraft,
    escrowDisbursementRows,
    formatScheduleAmount,
    getScheduleAmountTone,
    linkEscrowDisbursementToTransaction,
    printTaxReport,
    saveEscrowDisbursement,
    setCarryoverForScope,
    setEscrowDisbursementDraft,
    setTaxDayOverride,
    setTaxFiledAmountOverride,
    setTaxFiledAmountOverrideNote,
    startEditEscrowDisbursement,
    taxByPropertySchedule,
    taxByUnitSchedule,
    taxEscrowWarnings,
    taxFiledAmountOverrideInput,
    taxPrintUnitOptions,
    taxReportingSnapshot,
    taxScheduleBreakdown,
    taxSnapshot,
  } = useTaxWorkspaceController({
    activeTx,
    addAuditEntry,
    adjustedAssetDepreciationForYear,
    actions,
    appSettings,
    assets,
    currency,
    deMinimisThreshold,
    escrowDisbursements,
    effectiveLoanPaymentDeductibleInterest,
    effectiveTransactionDeductibleAmount,
    formatPropertyLabel,
    formatUnitLabel,
    getScheduleELineIdForTransaction,
    leases,
    loanPayments,
    loans,
    openConfirmDialog,
    properties,
    propertyFilter,
    propertyNameById,
    requirePermission,
    setNotice,
    setTaxCarryoverByScope,
    setTaxDayOverrides,
    setEscrowDisbursements,
    setTaxFiledAmountOverrides,
    setTaxPrintDialogOpen,
    setTaxPrintUnit,
    taxCarryoverByScope,
    taxDayOverrides,
    taxFiledAmountOverrides,
    taxPrintProperty,
    taxPrintScope,
    taxPrintUnit,
    todayIso,
    unitFilter,
    units,
    usePeriods,
    yearFilter,
  });
  const {
    applyOwnerStatementNoteTemplate,
    copyOwnerStatementBody,
    copyOwnerStatementSubject,
    exportOwnerCommunicationBundle,
    exportOwnerReport,
    exportOwnerStatement,
    exportOwnerStatementPdf,
    exportTenantStatement,
    exportTenantStatementPdf,
    ownerMonthlyRows,
    ownerMonthlyTotals,
    ownerStatementEmailDraftBody,
    ownerStatementEmailDraftSubject,
    ownerStatementPeriodLabel,
    ownerStatementPreparedBy,
    ownerStatementRange,
    ownerStatementRecipient,
    ownerStatementRecipientEmail,
    ownerStatementRecipientPhone,
    printOwnerStatement,
    printTenantStatement,
    selectedOwnerProperty,
  } = useStatementReportingController({
    activeTx,
    addAuditEntry,
    appSettings,
    buildPrintableStatementHtml,
    buildStatementBranding,
    copyTextToClipboard,
    currency,
    desktopStatementPdfApi,
    downloadTextAsFile,
    escapeHtml,
    formatPropertyLabel,
    formatStatementDateRangeLabel,
    formatStatementMonthLabel,
    formatStatementPresetLabel,
    formatUnitLabel,
    isTaxActive: view === "tax",
    leaseActualEndLabel,
    leaseDraft,
    leaseTenantLedgerSummary,
    leases,
    loanPayments,
    loans,
    monthStartIso,
    ownerStatementCustomEnd,
    ownerStatementCustomStart,
    ownerStatementNoteDraft,
    ownerStatementNoteMode,
    ownerStatementNoteTemplate,
    ownerStatementPreset,
    printHtmlDocument,
    properties,
    propertyFilter,
    propertyNameById,
    quarterStartIso,
    sanitizeFileNamePart,
    setNotice,
    setOwnerStatementCustomEnd,
    setOwnerStatementCustomStart,
    setOwnerStatementNoteDraft,
    setOwnerStatementNoteMode,
    taxScheduleBreakdown,
    taxSnapshot,
    tenantStatementCustomEnd,
    tenantStatementCustomStart,
    tenantStatementPreset,
    todayIso,
    unitFilter,
    units,
    usePeriods,
    yearFilter,
  });
  const {
    cancelLoanPaymentEdit,
    clearLoanDraft,
    deleteLoanPayment,
    editingLoanId,
    editingLoanPaymentId,
    effectiveLoanForDraft,
    loanDraft,
    loanEditorOpen,
    loanPaymentDraft,
    loanPaymentDraftTotalInput,
    loanPropertySummaries,
    recordLoanPayment,
    repairLoanFromHistory,
    resetLoanPaymentDraftForLoan,
    saveLoan,
    setEditingLoanPaymentId,
    setIsEditingLoanPaymentTotal,
    setLoanDraft,
    setLoanEditorOpen,
    setLoanPaymentDraft,
    setLoanPaymentDraftTotalInput,
    startAddLoan,
    startEditLoan,
    startEditLoanPayment,
    syncLoanBalanceFromHistory,
    visibleLoans,
  } = useLoanWorkspaceController({
    actions,
    confirmDestructiveActions: appSettings.confirmDestructiveActions,
    leases,
    loanPayments,
    loans,
    observedLoanDefaultsById,
    openConfirmDialog,
    planningAssumptions,
    prefetchDialog,
    properties,
    propertyFilter,
    requirePermission,
    setNotice,
    setView,
    todayIso,
    units,
    usePeriods,
  });

  const {
    acceptVisibleSafeSuggestions,
    applyAutomaticOcrToImportDraft,
    applyDocumentImportLinkSuggestion,
    applyDocumentLinkSuggestion,
    applySafeSuggestionsToDocument,
    applySuggestedDocumentTags,
    canAutoCreateExpenseFromSuggestion,
    canAutoCreateWorkOrderFromSuggestion,
    closeDocumentImportDialog,
    confirmAndDeleteDocument,
    createExpenseFromDocumentSuggestion,
    createExpenseTransactionsFromUtilitySections,
    createWorkOrderFromDocumentSuggestion,
    dismissDocumentExpenseReview,
    dismissDocumentWorkOrderReview,
    dismissVisibleExpenseQueue,
    getSafeDocumentLinkSuggestion,
    getSafeDocumentTagSuggestions,
    markDocumentWarningsReviewed,
    updateLinkedTransactionFromDocumentOcr,
    markVisibleDocumentsPendingOcr,
    onDocumentImportInputChange,
    openDocumentExternally,
    openDocumentImportPicker,
    openDocumentLinkedRecord,
    loadDocumentForReview,
    openDocumentPreview,
    openExpenseDraftFromDocument,
    openExpenseDraftFromUtilitySection,
    openWorkOrderDraftFromDocument,
    queueDocumentForOcr,
    reopenDocumentExpenseReview,
    reopenDocumentWorkOrderReview,
    removeDocumentRecordLink,
    reviewNextExpenseQueueItem,
    reviewNextWorkOrderQueueItem,
    runDocumentAiAnalysis,
    runVisibleDocumentOcr,
    saveDocumentExtractedText,
    saveDocumentOcrFieldCorrections,
    saveDocumentTags,
    saveImportedDocument,
  } = createDocumentWorkspaceController({
    actions,
    addAuditEntry,
    aiDocumentCopilotEnabled: appSettings.aiDocumentCopilotEnabled,
    aiOpenAiApiKey: appSettings.aiOpenAiApiKey,
    aiOpenAiModel: appSettings.aiOpenAiModel,
    appConfirmDestructiveActions: appSettings.confirmDestructiveActions,
    automaticDocumentOcrAvailable,
    buildDocumentAiContext,
    canAttachToTransaction,
    categories,
    closeConfirmDialog,
    createBlankDocumentImportDraft,
    createBlankForm,
    desktopDocumentAiApi,
    desktopDocumentOpenApi,
    desktopPersistenceApi,
    documentExpenseReviewRecords,
    documentImportDraft,
    documentImportExpenseSuggestion,
    documentImportInputRef,
    documentImportOcrRequestIdRef,
    documentImportWorkOrderSuggestion,
    documentSearch,
    documentStatusFilter,
    documentSupportsAutomaticOcr,
    documentWorkOrderReviewRecords,
    documentLinkSuggestionKindLabel,
    expenseQueueFocusDocumentId,
    expenseSuggestionReasonSummary,
    formatDocumentTags,
    getDocumentExpenseSuggestion,
    getDocumentExtractedFields,
    getDocumentImportLinkSuggestions,
    getDocumentImportSuggestedTags,
    getDocumentLinkSuggestions,
    getDocumentLinkedWorkOrder,
    getDocumentSuggestedTags,
    getDocumentUtilitySections,
    getDocumentWorkOrderSuggestion,
    getNextExpenseQueueRecord,
    getNextWorkOrderQueueRecord,
    leaseById,
    normalizeDocumentOcrStatus,
    normalizeExtractedDocumentText,
    openConfirmDialog,
    openLease,
    openTransaction,
    parseDocumentTags,
    prefetchDialog,
    properties,
    propertyFilter,
    readFileAsDataUrl,
    requirePermission,
    selectExpenseQueueFilter,
    selectWorkOrderQueueFilter,
    setDocumentAiBusyById,
    setDocumentBatchOcrBusy,
    setDocumentImportDialogOpen,
    setDocumentImportDraft,
    setDocumentImportOcrBusy,
    setDocumentImportOcrMessage,
    setDocumentOcrBusyById,
    setEditReturnView,
    setEditingTxnId,
    setExpenseQueueFocusDocumentId,
    setExpenseQueueShowDismissed,
    setForm,
    setNotice,
    setPendingDocumentExpenseSource,
    setPendingDocumentWorkOrderSource,
    setPendingTxnAttachment,
    setPropertyFilter,
    setRentAmountTouched,
    setSelectedDocument,
    setSelectedTxn,
    setUnitFilter,
    setView,
    setWorkOrderDraft,
    suggestDocumentType,
    todayIso,
    transactionById,
    transactions,
    transactionVendorMemories,
    txnAttachmentInputRef,
    unitFilter,
    units,
    visibleAutomaticOcrDocuments,
    visibleDocuments,
    visibleDocumentsMissingIndex,
    visibleExpenseReviewRecords,
    visibleWorkOrderReviewRecords,
    vendors,
    workOrderById,
    workOrderSuggestionReasonSummary,
  });

  const visibleSafeSuggestionCount = useVisibleSafeSuggestionCount({
    canAutoCreateExpenseFromSuggestion,
    canAutoCreateWorkOrderFromSuggestion,
    currency,
    getDocumentExpenseSuggestion,
    getDocumentExtractedFields,
    getDocumentWorkOrderSuggestion,
    getSafeDocumentLinkSuggestion,
    getSafeDocumentTagSuggestions,
    transactionById,
    visibleDocuments: view === "review" ? visibleDocuments : EMPTY_DOCUMENTS,
  });

  const {
    assetListForView,
    assetReviewInbox,
    loanReadinessSummary,
    loanReviewInbox,
    occupancyReadinessSummary,
    occupancyReviewInbox,
    setupChecklist,
    setupChecklistShowFull,
    taxReadinessSummary,
    tenantLedgerReadinessSummary,
    tenantLedgerReviewInbox,
  } = useReviewReadinessModel({
    activeTx,
    appSettings,
    assets,
    documents,
    effectiveLoanPaymentDeductibleInterest,
    filteredDocuments,
    isTaxReviewRelevantTransaction,
    leaseCoverageByProperty,
    leases,
    loanPayments,
    loans,
    maintenanceReviewInbox,
    persistenceHealth,
    properties,
    propertyFilter,
    tenantLedgerEntries,
    todayIso,
    transactionReviewInbox,
    units,
    usePeriods,
    workOrders,
    yearFilter,
  });

  const {
    exportScheduleEFilledPdf,
    exportScheduleEFormFdf,
    exportTaxDetailCsv,
    exportScheduleEReport,
    printTaxPacket,
    taxPacketSummary,
    taxReportingSummary,
  } = useTaxPacketReportingController({
    activeTx,
    adjustedAssetDepreciationForYear,
    assets,
    currency,
    documents,
    downloadTextAsFile,
    effectiveLoanPaymentDeductibleInterest,
    effectiveLoanPaymentRentalUsePct,
    effectiveTransactionDeductibleAmount,
    escapeHtml,
    formatPropertyLabel,
    formatUnitLabel,
    isTaxActive: view === "tax",
    leases,
    loanPayments,
    loans,
    printHtmlDocument,
    propertyFilter,
    propertyNameById,
    properties,
    sanitizeFileNamePart,
    taxFiledAmountOverrides,
    taxReadinessSummary,
    taxSnapshot: taxReportingSnapshot,
    tenantLedgerEntries,
    unitFilter,
    units,
    usePeriods,
    yearFilter,
  });

  const dashboardStatCards = useDashboardStatCards({
    dashboardCardSettings: appSettings.dashboardCards,
    dashboardTransactionCount: dashboardScopedTransactions.length,
    dashboardUnitAllocationWeight,
    deductibleExpensesTrend,
    grossRentTrend,
    metrics,
    taxReportingSummary,
    taxSnapshot,
    unitFilter,
  });

  const {
    deleteAsset,
    markTransactionCapitalImprovement,
    openAssetEditor,
    openAssetSourceTransaction,
    openAssetSourceWorkOrder,
    saveAsset,
    saveEditedAsset,
    startAddAsset,
    startCreateAssetFromTransaction,
    startCreateAssetFromWorkOrder,
  } = useAssetWorkspaceController({
    actions,
    appSettings,
    assetDraft,
    assetEditorDraft,
    documents,
    openConfirmDialog,
    openTransaction,
    prefetchDialog,
    properties,
    propertyFilter,
    requirePermission,
    setAssetDraft,
    setAssetEditorDraft,
    setAssetEditorOpen,
    setNotice,
    setView,
    todayIso,
    transactionById,
    workOrderById,
  });
  const { saveProperty } = usePropertyQuickAddController({
    actions,
    propertyDraft,
    requirePermission,
    resetPropertyDraft,
    setAssetDraft,
    setNotice,
    setPropertyFilter,
    setPropertyQuickAddOpen,
    setView,
  });

  const primaryAction = usePrimaryAction({
    openDashboardQuickAdd,
    openNewLeaseForUnit,
    propertyFilter,
    setPropertyQuickAddOpen,
    startAddAsset,
    startAddLoan,
    unitFilter,
    view,
  });

  const appWorkspaceProps = {
    acceptVisibleSafeSuggestions,
    actions,
    activeProperties,
    activeAccessRoleOption,
    activeTx,
    activityActionOptions,
    activityLog,
    activityEntityOptions,
    activityFilters,
    adjustedAssetDepreciationForYear,
    aiDocumentCopilotConfigured,
    aiDocumentCopilotReady,
    annualLoanSummary,
    appSettings,
    applyBankImportMatches,
    applyDocumentLinkSuggestion,
    applyOwnerStatementNoteTemplate,
    applySafeSuggestionsToDocument,
    applySuggestedDocumentTags,
    applyVendorMemoryToForm,
    assetById,
    assetListForView,
    assetReviewInbox,
    automaticDocumentOcrAvailable,
    autoBackupStatusLabel,
    autoOwnerUsePct,
    bankImportDefaults,
    bankImportFileName,
    bankImportImportedCount,
    bankImportInputRef,
    bankImportMatchCount,
    bankImportMatches,
    bankImportMatchRule,
    bankImportMatchRuleOptions,
    bankImportRows,
    bankImportSkippedRows,
    bankImportUnitOptions,
    bankImportUnmatchedRows,
    backupImportInputRef,
    backupValidationBusy,
    backupValidationResult,
    canAutoCreateExpenseFromSuggestion,
    canAutoCreateWorkOrderFromSuggestion,
    canCreateEditRecords,
    canDeleteRecords,
    canManageAccessProfile,
    canManageDataAdmin,
    canReviewDocuments,
    cancelLoanPaymentEdit,
    carryoverInputValue,
    carryoverScope,
    categoriesForFormType,
    checkForDesktopUpdates,
    clearBankImportPreview,
    clearEscrowDisbursementDraft,
    clearPlanningScenarioSelection,
    clearTaxFiledAmountOverride,
    clearTransactionForm,
    clonePlanningScenario,
    confirmAndDeleteDocument,
    confirmAndDeleteUsePeriod,
    confirmAndDeleteVendor,
    confirmResetTaxDayOverride,
    copyOwnerStatementBody,
    copyOwnerStatementSubject,
    copyPlanningMemo,
    copyTaxReviewNotes,
    createAutoBackupNow,
    createEscrowTransaction,
    createWorkOrder,
    createWorkOrderExpense,
    currentAppVersion,
    currentDataStatus,
    currentReleaseHistory,
    currentReleaseNotesEntry,
    dashboardAsOfDate,
    dashboardDensity: appSettings.dashboardDensity,
    dashboardLeases,
    dashboardScopedLeases,
    dashboardScopedTransactions,
    dashboardOpenReviewItems,
    dashboardPlanningWatch,
    dashboardPropertySnapshot,
    dashboardPropertySnapshotSummary,
    dashboardRentTransactions,
    dashboardStatCards,
    dashboardTransactions,
    deMinimisPreview,
    deMinimisThreshold,
    defaultEscrowLoanOptions,
    deleteEscrowDisbursement,
    deleteLoanPayment,
    deletePlanningActionItem,
    deletePlanningManualProject,
    deletePlanningScenario,
    deletePlanningScenarioEvent,
    describeDocumentOwnership,
    desktopDiagnosticEventClass,
    desktopDiagnosticPillClass,
    desktopDiagnosticsApi,
    desktopDiagnosticsBusy,
    desktopDiagnosticsCheckedAtLabel,
    desktopDiagnosticsRecentEvents,
    desktopDiagnosticsReport,
    desktopDocumentAiApi,
    desktopUpdateBadgeClass,
    desktopUpdateBusy,
    desktopUpdateCanRestart,
    desktopUpdateCheckedAtLabel,
    desktopUpdateMessage,
    desktopUpdateProgress,
    desktopUpdateReleaseDateLabel,
    desktopUpdateState,
    desktopUpdateStatusKey,
    desktopUpdateStatusLabel,
    desktopUpdaterAvailable,
    dismissedExpenseReviewCount,
    dismissedWorkOrderReviewCount,
    dismissDocumentExpenseReview,
    dismissDocumentWorkOrderReview,
    dismissVisibleExpenseQueue,
    documentAiBusyById,
    documentBatchOcrBusy,
    documentExpenseReviewRecordById,
    documentFilters,
    documentImportInputRef,
    documentOcrBusyById,
    documentWorkOrderReviewRecordById,
    documents,
    draftPlanningManualProjectFromTarget,
    editPlanningManualProject,
    editPlanningScenarioEvent,
    editingEscrowDisbursementId,
    editingLoanPaymentId,
    editingTxnId,
    editingVendorId,
    effectiveLoanForDraft,
    effectiveLoanPaymentDeductibleInterest,
    effectiveUpdateReleaseNotes,
    escrowDisbursementDraft,
    escrowDisbursementRows,
    expectedRecurringTransactions,
    expenseQueueShowDismissed,
    exportDataBackup,
    exportLatestAutoBackup,
    exportOwnerCommunicationBundle,
    exportOwnerReport,
    exportOwnerStatement,
    exportOwnerStatementPdf,
    exportPlanningMemoPdf,
    exportPlanningMemoText,
    exportPlanningReport,
    exportScheduleEFilledPdf,
    exportScheduleEFormFdf,
    exportScheduleEReport,
    exportTaxDetailCsv,
    filteredActivityLog,
    filteredDocuments,
    focusedExpenseQueueDocumentId,
    form,
    formatDesktopUpdateDate,
    formatPropertyLabel,
    formatScheduleAmount,
    formatUnitLabel,
    getDocumentExpenseSuggestion,
    getDocumentExtractedFields,
    getDocumentLinkedWorkOrder,
    getDocumentLinkSuggestions,
    getDocumentSuggestedTags,
    getDocumentUtilitySections,
    getDocumentWorkOrderSuggestion,
    getPlanningRentStrategy,
    getPlanningTurnoverInput,
    getPlanningUnitOverride,
    getSafeDocumentLinkSuggestion,
    getSafeDocumentTagSuggestions,
    getScheduleAmountTone,
    getSuggestedFieldOptions,
    getUnitOccupancyPeriods,
    getUnitStatusForDate,
    hiddenMaintenanceVendorCount,
    importReviewedBankRows,
    incomeCategoriesForForm,
    installDesktopUpdateNow,
    isHistoricalDashboard,
    isTaxReviewRelevantTransaction,
    leaseActualEndLabel,
    leaseAutomationLastRunLabel,
    leaseCoverageByProperty,
    leaseDocCountById,
    leases,
    ledgerCategories,
    ledgerFilters,
    ledgerTransactions,
    linkEscrowDisbursementToTransaction,
    loadDemoData,
    loadPlanningScenario,
    loanPaymentDraft,
    loanPaymentDraftTotalInput,
    loanPayments,
    loanPropertySummaries,
    loanReadinessSummary,
    loanReviewInbox,
    loans,
    maintenanceReviewInbox,
    maintenanceRollup,
    maintenanceStatusFilter,
    maintenanceStatusSummary,
    maintenanceTotalCost,
    maintenanceVendors,
    maintenanceVisibleWorkOrders,
    markTransactionCapitalImprovement,
    markTransactionsTaxReviewed,
    markTransactionSupportUnavailable,
    markDocumentWarningsReviewed,
    updateLinkedTransactionFromDocumentOcr,
    markVisibleDocumentsPendingOcr,
    mileagePreview,
    navigateWithDashboardContext,
    observedLoanDefaultsById,
    occupancyReadinessSummary,
    occupancyReviewInbox,
    onBackupImportInputChange,
    onBankImportInputChange,
    onBankImportMatchRuleChange,
    onDocumentImportInputChange,
    onStatementLogoInputChange,
    onTransactionAttachmentInputChange,
    onWorkOrderAttachmentInputChange,
    openAssetEditor,
    openAssetSourceTransaction,
    openAssetSourceWorkOrder,
    openBackupImportPicker,
    openBankImportPicker,
    openBankImportReview,
    openCurrentReleaseNotesDialog,
    openDesktopDataFolder,
    openDocumentImportPicker,
    openDocumentLinkedRecord,
    loadDocumentForReview,
    openDocumentPreview,
    openDashboardQuickAddForScope,
    openExpenseDraftFromDocument,
    createExpenseTransactionsFromUtilitySections,
    openExpenseDraftFromUtilitySection,
    openLease,
    openLeaseForUnit,
    openNewLeaseForUnit,
    openOccupancyEditor,
    openPlanningWorkspace,
    openPropertyFromSnapshot,
    openTransaction,
    openTransactionAttachmentPicker,
    openUpdateReleaseNotesDialog,
    openWorkOrderAttachmentPicker,
    openWorkOrderDocuments,
    openWorkOrderDraftFromDocument,
    ownerContactDefaults,
    ownerMonthlyRows,
    ownerMonthlyTotals,
    ownerStatementEmailDraftBody,
    ownerStatementEmailDraftSubject,
    ownerStatementPeriodLabel,
    ownerStatementPreparedBy,
    ownerStatementRange,
    ownerStatementRecipient,
    ownerStatementRecipientEmail,
    ownerStatementRecipientPhone,
    pendingDocumentExpenseSource,
    pendingDocumentWorkOrderSource,
    pendingExpenseReviewCount,
    pendingHighConfidenceExpenseReviewCount,
    pendingHighConfidenceWorkOrderReviewCount,
    pendingTxnAttachment,
    pendingWorkOrderReviewCount,
    persistenceHealth,
    persistenceLastError,
    performanceMetrics: { ...performanceMetrics, ...runtimePerformanceMetrics },
    planningActionItems,
    addPlanningActionItem,
    planningActiveScenario,
    planningActiveScenarioId,
    planningAssumptionAuditRows,
    planningAssumptions,
    planningBaselineScenario,
    planningBaselineScenarioId,
    planningCapitalChartData,
    planningCapitalMonthlyTarget,
    planningCapitalRunway,
    planningCapitalTargetsMerged,
    planningCapitalTargetSections,
    planningCapitalTimeline,
    planningDataConfidence,
    planningDebtPayoff,
    planningDebtPayoffPlan,
    planningDecisionComparison,
    planningDecisionDashboard,
    planningEventDraft,
    planningEventPropertyId,
    planningEventUnitOptions,
    planningExcludedBuildingAssetCount,
    planningExitAnalysis,
    planningExitPlan,
    planningFinancingComparison,
    planningForecastOptions,
    planningForecastOptionInputs,
    planningGoals,
    planningGoalStatus,
    planningHealthSummary,
    planningHorizonDisplayMetrics,
    planningHorizonMonths,
    planningHorizonShortLabel,
    planningManualProjects,
    planningMemoText,
    planningMilestones,
    planningMustFundWarnings,
    planningNearTermCapitalCost,
    planningNearTermCapitalTargets,
    planningNearTermReserveTarget,
    planningNextCapitalTarget,
    planningOutcomeHighlights,
    planningOverviewJumpCards,
    planningProjectDraft,
    planningProjectLinkedAssetOptions,
    planningProjectPropertyId,
    planningProjectUnitOptions,
    planningPropertySnapshots,
    planningRecommendations,
    planningRecommendedMoves,
    planningRentStrategies,
    planningRentStrategy,
    planningReserveGap,
    planningReserveSummary,
    planningReviewInbox,
    planningRows,
    planningSavedScenarios,
    planningScenarioChartData,
    planningScenarioComparisons,
    planningScenarioComparisonsExtended,
    planningScenarioDiffRows,
    planningScenarioEvents,
    planningScenarioIsDirty,
    planningScenarioNameDraft,
    planningScenarioNotesDraft,
    planningScenarioRange,
    planningScenarioTimelineRows,
    planningScenarioTimelineVisual,
    planningScopeLabel,
    planningScopeUnits,
    planningSensitivityRows,
    planningSubtab,
    planningSubtabGuide,
    planningSummary,
    planningTaxProjection,
    planningTriggers,
    planningTriggerAlerts,
    planningTurnoverPlanner,
    planningUnitEconomicsRows,
    planningUnitFilterIgnored,
    planningUpcomingChanges,
    postDueRecurringTransactions,
    preview,
    printOwnerStatement,
    printPlanningMemo,
    printTaxPacket,
    properties,
    propertyFilter,
    propertyNameById,
    propertyOwnerDrafts,
    queueDocumentForOcr,
    realDataChecklist,
    recurringTemplates,
    recurringThroughDate,
    reconcileTransactions,
    recordLoanPayment,
    reloadDesktopPersistenceData,
    restorePointBusy,
    removeDocumentRecordLink,
    reopenDocumentExpenseReview,
    reopenDocumentWorkOrderReview,
    repairLoanFromHistory,
    resetLoanPaymentDraftForLoan,
    resetPlanningEventDraft,
    resetPlanningProjectDraft,
    resetPlanningWorkspace,
    resetToDefaults,
    resetVendorEditor,
    restoreLocalAdminAccess,
    reviewNextExpenseQueueItem,
    reviewNextWorkOrderQueueItem,
    roleAccessSummary,
    runDesktopDiagnostics,
    runDocumentAiAnalysis,
    runLeaseAutomationNow,
    runVisibleDocumentOcr,
    saveDocumentExtractedText,
    saveDocumentOcrFieldCorrections,
    saveDocumentTags,
    saveEscrowDisbursement,
    savePlanningManualProject,
    savePlanningManualProjectFromTarget,
    savePlanningScenarioAsNew,
    savePlanningScenarioBranch,
    savePlanningScenarioEvent,
    savePropertyOwnerContact,
    saveTransaction,
    saveVendor,
    scopedLeaseAutomationReminders,
    seeAllLeases,
    seeAllNeedsReview,
    seeAllProperties,
    seeAllTransactions,
    selectExpenseQueueFilter,
    selectedOwnerProperty,
    selectedTxn,
    selectWorkOrderQueueFilter,
    setBankImportDefaults,
    setCarryoverForScope,
    setEscrowDisbursementDraft,
    setExpenseQueueShowDismissed,
    setForm,
    setEditingLoanPaymentId,
    setIsEditingLoanPaymentTotal,
    setLoanPaymentDraft,
    setLoanPaymentDraftTotalInput,
    setMaintenanceStatusFilter,
    setNotice,
    setPendingTxnAttachment,
    setPlanningAssumptions,
    setPlanningBaselineScenarioId,
    setPlanningDebtPayoffPlan,
    setPlanningEventDraft,
    setPlanningExitPlan,
    setPlanningForecastOptions,
    setPlanningGoals,
    setPlanningProjectDraft,
    setPlanningRentStrategy,
    setPlanningScenarioNameDraft,
    setPlanningScenarioNotesDraft,
    setPlanningSubtab,
    setPlanningTriggers,
    setPlanningTurnoverInput,
    setPlanningUnitOverride,
    setPropertyFilter,
    setPropertyOwnerDrafts,
    setPropertyQuickAddOpen,
    setRentAmountTouched,
    setSetting,
    setSettingsSectionCollapsed,
    setSetupChecklistOverride,
    setTaxDayOverride,
    setTaxFiledAmountOverride,
    setTaxFiledAmountOverrideNote,
    setVendorDraft,
    setView,
    setWorkOrderDraft,
    settingsSectionCollapsed,
    setupChecklist,
    setupChecklistShowFull,
    showDeMinimisControls,
    startCreateAssetFromTransaction,
    startCreateAssetFromWorkOrder,
    startEditEscrowDisbursement,
    startEditingVendor,
    startEditLoan,
    startEditLoanPayment,
    statementLogoInputRef,
    syncLoanBalanceFromHistory,
    taxByPropertySchedule,
    taxByUnitSchedule,
    taxEscrowWarnings,
    taxFiledAmountOverrideInput,
    taxPacketSummary,
    taxReadinessSummary,
    taxReportingSummary,
    taxReviewCpaNotes,
    taxReviewOpenCount,
    taxReviewSections,
    taxScheduleBreakdown,
    taxSnapshot,
    taxWorkspaceUiProps,
    tenantLedgerEntries,
    tenantLedgerReadinessSummary,
    tenantLedgerReviewInbox,
    transactionById,
    transactionReviewById,
    transactionReviewInbox,
    transactions,
    txnAttachmentInputRef,
    toggleDashboardCardSetting,
    toggleSetupChecklistShowFull,
    todayIso,
    unitFilter,
    unitStatusLabel,
    units,
    updatePlanningActionItem,
    updatePlanningScenario,
    updateReleaseNotesEntry,
    updateTargetVersion,
    usePeriods,
    useTransactionDatesAsServicePeriods,
    validateLatestBackup,
    vendorById,
    vendorDraft,
    vendorMemorySuggestion,
    view,
    visibleLoans,
    visibleAutomaticOcrDocuments,
    visibleDocuments,
    visibleDocumentsMissingIndex,
    visibleExpenseReviewRecords,
    visibleSafeSuggestionCount,
    workOrderAttachmentInputRef,
    workOrderDocumentCountById,
    workOrderDraft,
    WORK_ORDER_PRIORITY_OPTIONS,
    workOrderUnitOptions,
    workOrders,
    yearFilter,
    yearScopedLoanPayments,
  };

  const appDialogProps = {
    actions,
    activeProperties,
    activeTx,
    aiDocumentCopilotConfigured,
    aiDocumentCopilotReady,
    appSettings,
    applyAutomaticOcrToImportDraft,
    applyBankImportVendorMemoryToDraft,
    applyDocumentImportLinkSuggestion,
    assetEditorDraft,
    assetEditorOpen,
    automaticDocumentOcrAvailable,
    bankImportReviewDrafts,
    bankImportReviewOpen,
    bankImportReviewRows,
    bankImportTypeOptions,
    buildBankImportReviewDraft,
    canCreateEditRecords,
    canDeleteRecords,
    canReconcileRecords,
    categories,
    categoriesForFormType,
    clearLoanDraft,
    clearTenantLedgerEntryDraft,
    closeConfirmDialog,
    closeDocumentImportDialog,
    closeLeaseEditor,
    closeReleaseNotesDialog,
    confirmAndDeleteDocument,
    confirmAndDeleteLease,
    confirmAndDeleteTenantLedgerEntry,
    confirmAndDeleteUsePeriod,
    confirmDeleteTransaction,
    confirmDialog,
    createBlankForm,
    currentReleaseHistory,
    dashboardQuickAddOpen,
    defaultLifeForAssetType,
    deleteAsset,
    desktopDocumentOpenApi,
    desktopUpdateState,
    displayedLeaseTenantLedgerRows,
    documentAiBusyById,
    documentImportDialogOpen,
    documentImportDraft,
    documentImportExpenseSuggestion,
    documentImportExtractedFields,
    documentImportLinkSuggestions,
    documentImportOcrBusy,
    documentImportOcrMessage,
    documentImportSuggestedTags,
    documentImportUnitOptions,
    documentImportUtilitySections,
    documentImportWorkOrderSuggestion,
    documentLinkSuggestionKindLabel,
    documents,
    documentTagSuggestionSourceLabel,
    editingLoanId,
    editingTenantLedgerEntryId,
    editingUsePeriodId,
    exportTenantStatement,
    exportTenantStatementPdf,
    form,
    formatPropertyLabel,
    formatUnitLabel,
    formatUsPhone,
    getBankImportRowVendorMemory,
    getTransactionReview,
    getUnitOccupancyPeriods,
    getUnitStatusForDate,
    handleClearSelectedTxnOwnerUseOverride,
    handleDeleteSelectedTxn,
    handleDuplicateSelectedTxn,
    handleEditSelectedTxn,
    handleMarkSelectedTxnTaxReviewed,
    handleToggleSelectedTxnReconciled,
    handleToggleSelectedTxnTaxChecked,
    handleUseSelectedTxnDateAsServicePeriod,
    handleVoidSelectedTxn,
    importReviewedBankRows,
    incomeCategoriesForForm,
    isTaxReviewRelevantTransaction,
    isTenantLedgerKindAllowedForTreatment,
    leaseDraft,
    leaseEditorMode,
    leasePdfInputRef,
    leaseReminderKindLabel,
    leaseReminderToneClass,
    leaseTenantLedgerHeadline,
    leaseTenantLedgerRowById,
    leaseTenantLedgerSort,
    leaseTenantLedgerSummary,
    leaseValidationDialog,
    leases,
    loanDraft,
    loanEditorOpen,
    markTransactionCapitalImprovement,
    normalizeTenantLedgerAccountingTreatment,
    onLeasePdfInputChange,
    onTransactionInlineAttachmentChange,
    openAssetSourceTransaction,
    openAssetSourceWorkOrder,
    openDocumentExternally,
    openDocumentPreview,
    createExpenseTransactionsFromUtilitySections,
    openExpenseDraftFromUtilitySection,
    openLeasePdfPicker,
    openLinkedTenantLedgerTransaction,
    openTransactionInlineAttachmentPicker,
    ownerContactDefaults,
    printTaxReport,
    printTenantStatement,
    properties,
    propertyDraft,
    propertyFilter,
    propertyNameById,
    propertyQuickAddOpen,
    recommendedTenantLedgerAccountingTreatment,
    recommendedTenantLedgerKindForTreatment,
    releaseNotesDialog,
    releaseNotesDialogDateLabel,
    releaseNotesDialogEntry,
    releaseNotesDialogLines,
    releaseNotesDialogSummary,
    releaseNotesDialogTitle,
    releaseNotesDialogVersion,
    runDocumentAiAnalysis,
    saveEditedAsset,
    saveImportedDocument,
    saveLease,
    saveLoan,
    saveProperty,
    saveTenantLedgerEntry,
    saveTransaction,
    saveUnitOccupancyPeriod,
    selectedDocument,
    selectedDocumentAiAnalysis,
    selectedDocumentExtractedFields,
    selectedDocumentUtilitySections,
    selectedLeaseAutomationReminders,
    selectedLeaseDocuments,
    selectedTransactionDocuments,
    selectedTxn,
    selectedTxnLinkedWorkOrder,
    selectedTxnReconcileWarning,
    selectedTxnReconcileWarningText,
    selectedTxnReviewFocusKey,
    selectedTxnToggleReconcileDisabled,
    setAssetEditorDraft,
    setAssetEditorOpen,
    setBankImportReviewOpen,
    setDashboardQuickAddOpen,
    setDocumentImportDialogOpen,
    setDocumentImportDraft,
    setEditingUsePeriodId,
    setForm,
    setLeaseDraft,
    setLeaseEditorMode,
    setLeaseTenantLedgerSort,
    setLoanDraft,
    setLoanEditorOpen,
    setPendingTxnAttachment,
    setPropertyDraft,
    setPropertyQuickAddOpen,
    setRentAmountTouched,
    setSelectedDocument,
    setSelectedTxn,
    setTenantLedgerDraft,
    setTenantStatementCustomEnd,
    setTenantStatementCustomStart,
    setTenantStatementPreset,
    setTxnToDelete,
    setUsePeriodDraft,
    setLeaseValidationDialog,
    startCreateAssetFromTransaction,
    startTenantLedgerEntryEdit,
    taxPrintDialogOpen,
    taxPrintDialogStateProps,
    taxPrintUnitOptions,
    tenantLedgerDraft,
    tenantStatementCustomEnd,
    tenantStatementCustomStart,
    tenantStatementPreset,
    todayIso,
    transactionById,
    transactions,
    txnAttachmentInputRef,
    txnInlineAttachmentInputRef,
    txnToDelete,
    unitFilter,
    unitStatusLabel,
    units,
    updateBankImportReviewDraft,
    usePeriodDraft,
    usePeriods,
    workOrderById,
    workOrderSuggestionConfidenceLabel,
    workOrders,
    yearFilter,
  };



  return (
    <div className={`rt-app-shell min-h-screen p-3 sm:p-4 ${appSettings.theme === "dark" ? "theme-dark bg-slate-950 text-slate-100" : "theme-light bg-slate-100 text-slate-900"}`}>
      <div className={`mx-auto grid max-w-[1720px] grid-cols-[minmax(0,1fr)] gap-4 lg:items-start ${sidebarCollapsed ? "lg:grid-cols-[72px_1fr]" : "lg:grid-cols-[200px_1fr]"}`}>
        <AppSidebar
          currentView={currentView}
          navItems={navItems}
          prefetchWorkspace={prefetchWorkspace}
          properties={activeProperties}
          propertyFilter={propertyFilter}
          setPropertyFilter={setPropertyFilter}
          setSidebarCollapsed={setSidebarCollapsed}
          setUnitFilter={setUnitFilter}
          setView={setView}
          setYearFilter={setYearFilter}
          sidebarCollapsed={sidebarCollapsed}
          unitFilter={unitFilter}
          unitFilterOptions={unitFilterOptions}
          view={view}
          yearFilter={yearFilter}
        />
        <main className="min-w-0 space-y-4">
          <AppHeaderCard
            currentView={currentView}
            dashboardAsOfDate={dashboardAsOfDate}
            dashboardFiltersSummary={dashboardFiltersSummary}
            dashboardPlanningWatch={dashboardPlanningWatch}
            filterControls={{
              properties: activeProperties,
              propertyFilter,
              setPropertyFilter,
              setUnitFilter,
              setYearFilter,
              unitFilter,
              unitFilterOptions,
              yearFilter,
            }}
            notice={notice}
            prefetchDialog={prefetchDialog}
            primaryAction={primaryAction}
            settingsSavedText={SETTINGS_SAVED_TEXT}
            settingsSavedVisible={settingsSavedVisible}
            setupChecklist={setupChecklist}
            taxReadinessSummary={taxReadinessSummary}
            view={view}
          />

          <AppWorkspaces {...appWorkspaceProps} />
        </main>
      </div>
      <AppDialogs {...appDialogProps} />
    </div>
  );
}
